```{r executive, echo = FALSE}
assessmentyear <- as.numeric(format(Sys.Date(), "%Y")) - 1
area_long <- paste0(tolower(params$area), "ern ")
n_stocks <- xfun::numbers_to_words( length(get_groups(info_groups)))
executive <- list()
executive[["stock"]] <- paste0("This assessment reports the status of ",
  spp, " (_", spp.sci, "_) off the ", tolower(params$area), "ern ", coast,
  " coast using data through ", assessmentyear, ".")
```
# Executive summary{-}

## Stock{-}

```{asis executive-summary-stock, echo = TRUE}
`r executive[["stock"]]`
As per previous assessments, `r spp` were separated into `r n_stocks` stocks and
this document contains information summarizing both stocks as well as
detailed information for the `r area_long` stock.
It does not include Alaskan, Canadian, or Mexican populations and
assumes that these flanking populations do not contribute to the stock being assessed here.
```

## Landings{-}
Replace text.

## Data and assessment{-}
Replace text.

## Stock biomass{-}
Replace text.

## Recruitment{-}
Replace text.

## Exploitation status{-}
Replace text.

## Reference points{-}
Replace text.

## Management performance{-}
Replace text.

## Unresolved problems and major uncertainties{-}
Replace text.

## Decision table{-}
Replace text.

## Research and data needs{-}
```{r results = "asis"}
sa4ss::read_child("research-and-data-needs.Rmd")
```
