## Summary of management history and performance

### Commercial fishery

Prior to 1977, `r spp` stocks in the northeast Pacific were managed by the
Canadian Government within its waters and
by the individual states in waters out to three miles off their respective coastlines.
With the implementation of the \gls{msfcma} in 1976,
primary responsibility for the management of groundfish stocks off
Washington, Oregon, and California shifted from the states to the \gls{pfmc}.
The U.S. west coast \gls{abc} for `r spp`  was set at 7,000 mt,
but catch was consistently below this level.
In 1994, a \gls{hg} of 4,000 mt was set.
In 1995, both the \gls{abc} and \gls{hg} were dropped to 2,400 mt
based on results of Jagielo [-@jagielo1994assessment].
Further reductions were made in 1998
to 1,532 mt with a \gls{hg} of 838 mt based on an assessment of the
northern area [@jagielo1997assessment].

In 1995 a minimum size limit for the limited entry fishery was imposed
for the first time that restricted landed `r spp` to be at least 22 inches.
This size restriction matched the restriction within the recreational fishery
and trawl-caught `r spp`, with a 100 lb exception for the latter.
The minimum size was increased to 24 inches in 1998.
Minimum size across areas diverged in 2000 [@jagielo2000assessment], when the minimum size of
`r spp` landed south of \CapeM latitude in the
limited entry fixed gear fishery increased to 26 inches.
Currently, the minimum size limits for the limited entry fixed gear
and open access commercial fisheries are
22 inches north of of 42$\circ$ N. latitude and
24 inches south of 42$\circ$ N. latitude.
This corresponds to fish 18 and 19.5 inches after the head has been removed.

Trip limits on commercial `r spp` catch were first instituted in 1995,
when a 20,000 lbs/month limit was imposed.
In 1998, a two-month cumulative limit of 1,000 lbs was imposed.
Since then, management of the fishery has occurred through
individual-year \gls{abc} and \gls{oy} levels (Table \@ref(tab:management-refpoints)).

The \gls{pfmc} implemented an initial Rebuilding Plan in 2000
with size and seasonal limitations in the recreational fishery and
a change to limited entry and open access sectors in the commercial fishery.
Additionally, the coastwide \gls{abc} was reduced
from 960 mt to 700 mt based on a new assessment of the southern area [@pfmclingcod1999] and
the rebuilding plan [@jagielo1999rebuildingplan].
In the commercial fishery sector, \glspl{hg} in 2000 were reduced by over 80\%
from 1998 limits.
To achieve these restricted harvests,
all commercial fishing for `r spp`  was closed for six months during the year,
from January to April and November to December.
During the open period between April and November,
all commercial vessels were limited to 400 lbs per month and
non-trawl vessels had a minimum size limit of
26 inches south of Cape Mendocino (\CapeM) and
24 inches to the north of Cape Mendocino.

Between 2000 and 2005, while the fishery was rebuilding,
cumulative trip limits were very low, at 800 lbs bimonthly,
with frequent closures.
After 2006, \glspl{abc} and trip limits were increased,
with a bimonthly limit of 1,200 lbs.
Concurrently, \glspl{mpa} in California,
\glspl{rca}, and the \gls{cca} were established.
In these areas, take of all groundfish is prohibited within specified
depths, habitats, and locations.

Monitoring of the commercial catch of `r spp` began earlier compared 
to some other U.S. West Coast groundfish species, and `r spp` have 
almost always been their own market category for recording and sampling purposes.

At-sea monitoring of the commercial catch of `r spp` began when the 
West Coast Groundfish Observer Program (WCGOP) was started in 2002.
Initially about 20\% of trawl trips and a smaller faction of fixed-gear trips were
randomly chosen for observer coverage. In 2011, the limited entry trawl 
sector became a catch share program and has had 100\% observer coverage since 
that time. In recent years electronic monitoring (EM) has replaced human 
observers on a subset of the vessels in the limited entry trawl sector.
The number of bottom trawl trips with EM monitoring has increased from 24 in 2015 
to 193 in 2019, however that still represents a small minority of the vessels and trips.

### Recreational fishery

Recreational regulations for `r spp` were established in 1976 in Oregon
that included a five fish sub-bag limit for marine species.
Bag limits in Oregon were reduced to three fish in 1978 and remained at three until 1999.
Regulations in Washington were established in 1994 and included
a bag limit of three fish. In California,
a bag limit of five fish was implemented in 1994 and
a minimum size limit of 22 inches in Washington and California.
The 22 inch minimum size limit was adopted in Oregon in 1995 and
increased to 24 inches in all three states in 1998.
In 1998, the bag limit in Washington and California dropped to two fish per day.
Oregon followed suite in 1999, and
the two-fish bag limit largely remained coastwide until 2008.
The minimum size limit for California increased in 2000 to 26 inches.

Between 2000 and 2004,
the California recreational bag limit dropped to 1 fish per day and
the size limit increased from 26 to 30 inches.
Oregon's bag limit fluctuated between one and two fish per day.
Regulations have become less restrictive since the rebuilding period.
In 2015, the bag limit increased to 3 fish per day in California,
while the two-fish bag limit was retained in Oregon and Washington.
A size limit of 22 inches was adopted in all three states.
More recently, the bag limit in California has decreased to 2 fish per day.
In Oregon, there have been multiple recreational groundfish in-season closures
to reduce impacts to overfished rockfish.
