# Data

Descriptions of each data source included in the model (Figure \ref{fig:data-plot})
and sources that were explored but not included
are provided below.

## Fishery-Dependent Data

```{r render-catch, results = "asis"}
sa4ss::read_child(file.path("catch.Rmd"))
```

### \Glsentrylong{cpue} (\glsentryshort{cpue})

```{r render-cpue, results = "asis", cache = TRUE, eval = grepl("North", params$area)}
sa4ss::read_child(file.path("commcpueor.Rmd"))
sa4ss::read_child(file.path("reccpuewa.Rmd"))
sa4ss::read_child(file.path("reccpueor.Rmd"))
```

### Unused fishery-dependent data

```{r render-24data-notused, results = "asis"}
sa4ss::read_child(file.path("24data-notused.Rmd"))
```

## Fishery-Independent data

```{r render-standardsurveys, results = "asis"}
sa4ss::read_child(file.path("21s-wcgbts.Rmd"))
sa4ss::read_child(file.path("21s-tri.Rmd"))
```

```{r render-surveysouth, results = "asis", opts.label = 'south'}
sa4ss::read_child(file.path("21s-hkl.Rmd"))
```

```{r render-remainingsurveys, results = "asis"}
sa4ss::read_child(file.path("21s-ccfrp.Rmd"))
sa4ss::read_child(file.path("21s-lam-research.Rmd"))
sa4ss::read_child(file.path("21s-aslope.Rmd"))
```

### Unused fishery-independent data

```{r render-29data-notused, results = "asis"}
sa4ss::read_child(file.path("29data-notused.Rmd"))
```
