### Lam Research

In collaboration with the NWFSC and Moss Landing Marine Labs, lingcod in nearshore 
and offshore rocky reef habitats were collected between January 2016 and January 
2017 via hook and line on chartered CPFVs (@Lam-thesis). Sixteen latitudinal distinct sampling 
sites, or ports, were chosen from northern Washington to southern California. 85 
to 120 individuals were caught per port (N = 1,784, 922 Males, 862 Females) using 
methods identical to those used by the onboard recreational lingcod fishery 
except that shorts were retained (individuals smaller than the legal-size limit 
of 22 inches) and areas closed to recreational harvest were occasionally utilized 
(CDFW Permit #SC-6477, ODFW Permit #20237, WDFW Permit ID Samhouri 16-138). 
This was to ensure an even distribution of size and age classes from each port 
for purposes of comparing `r spp` von Bertalanffy growth curves by spatially 
explicit regions. Of the total fish samples, 32 were sampled on CCFRP trips and so to avoid double 
counting were excluded. Four addition samples had no year associated with them, and
were excluded. Length compositions from this survey were used as numbers of fish, 
and were not expanded. Lengths were measured in total length, and were converted to
fork length following conversions from Laidig et al. @Laidig_conversions. Total
and fork lengths for `r spp` were generally very similar given the tail shape 
of `r spp`. 
Figure \ref{fig:lam-lenComp} shows the length frequency distributions. 
Table \ref{tab:sample-size-length} shows sample sizes.


A random stratified subsample by size and sex was selected per region for ageing and genetics analysis. 
The age composition data are therefore used as CAAL, and are not expanded.
Figure \ref{fig:lam-ageComp} shows the age frequency distributions. 
Table \ref{tab:sample-size-length} shows sample sizes.



