#### \acrlong{s-aslope}

The \gls{s-aslope} operated during the months of October to November aboard the R/V _Miller Freeman_.
Partial survey coverage of the U.S. west coast occurred during the years 1988-1996 and complete coverage (north of 34\textdegree 30\textquotesingle S latitude) during the years 1997 and 1999-2001.
Typically, only these four years that are seen as complete surveys are included in assessments.

Sample sizes of `r spp` were low during these four complete years, with 119 samples across
55 tows coastwide. Given that `r spp` are primarily a shelf species, data from this
survey was not included in the model. 

#### \gls{nwfsc} \gls{s-aslope}

The \gls{nwfsc} also operated \gls{s-aslope} during the years 1998-2002. Coastwide, 184
`r spp` were sampled across 64 tows.
Data from this survey were not included in the model because
`r spp` is primarily a shelf species and sample sizes were low.

#### \Glsentrylong{iphc} longline survey

Data from \gls{iphc} longline survey were examined in the past for their utility
in measuring \gls{cpue} from fixed gear.
However, depth and hook size are not appropriate for `r spp`.

```{asis, opts.label='north', echo=TRUE}
#### Oregon video lander survey

\Gls{odfw} provided density estimates and a range of estimated population
abundances from underwater video lander data for `r spp`.
The lander data was collected over nine years by \gls{odfw}
[@rasmuson2020]. The data includes information from
ten independent studies carried out in both nearshore rocky reefs
coastwide, as well as select reef structures offshore of the central coast of
Oregon. Underwater video landers are stationary platforms consisting of one
to three video cameras. Landers used in deeper water employ advanced
lighting systems for optimal viewing of fish and benthic habitat. Ambient
light is used in shallow surveys. The variability in detection range by
depth is an important factor to consider when deriving fish density from
lander data.

Variability in range, and therefore area viewed, directly influences estimates of fish
abundance. Thus, density estimates were calculated using five
estimates of range,
average range,
+/- one standard deviation from the mean, and
maximum and minimum ranges.
The area viewed is calculated using both the range and the horizontal field of
view. This viewed area was then combined with fish-count data to generate
fish densities. Count data were provided from Rasmuson et al. [-@rasmuson2020].
As expected, the viewed range has a large effect on the calculated density,
with larger ranges resulting in a lower density of fish. There is
no way to know which range most accurately reflects the true density of
fish, and thus, multiple range estimates were combined into a single density
estimate using a weighted arithmetic mean.
Area viewed increases exponentially suggesting the use of a
geometric mean may be more appropriate than an arithmetic mean.
The geometric mean density was calculated
three ways to address the presence of zeros in the data.
Abundance estimates (numbers of fish) were calculated by multiplying the density
estimate by an estimate of the habitat area. Coastwide habitat area was
limited to primary or secondary habitat containing hard substrate. The
western boundary was defined as the 200 m contour based on the depth of the
continental shelf-break. The eastern boundary was based on the shallowest
lander observation for each species. `r Spp` were
observed on lander video in water as shallow as 4 m; therefore, the 0 m
contour was used. It should be noted that, while the depth range of the
lander surveys conducted by \gls{odfw} extends to 212 m, the majority of
lander surveys have been conducted in either nearshore rocky reefs or at
Stonewall Bank \gls{rca} on the central Oregon coast.

For `r spp`, density estimates ranged from
0.020 ± 0.052 (number fish / $m^2$ ± standard deviation) to
0.793 ± 1.850 for the
maximum range method and the third geometric mean method, respectively.
The estimated habitat area was 1,940 thousands $km^2$.
Abundance estimates ranged from 38.8 ± 100.8 (millions of fish ± standard deviation)
to 1,537 ± 3,585. Estimates of abundance from the five range
models produced similar results to the weighted arithmetic mean, ranging from
38.8 ± 100.8 for the maximum range to 170.5 ± 472.8
for the minimum range.
These were generally considered more plausible than
the results based on the geometric means.

#### Oregon Marine Reserve Program

\Gls{odfw} Marine Reserve Program in has routinely monitored state
marine reserves and associated comparison areas since 2011.
Surveys in 2011 and 2012 only visited Redfish Rocks marine reserve.
Surveys from 2013 – 2019 include reserves and
comparison areas from four marine reserves,
Redfish Rocks, Cape Falcon, Cape Perpetua, and Cascade Head
(Table \@ref(tab:fi-index-ormarres-mr)).
Each of these marine reserves has one to three associated comparison areas.
Comparison areas are specifically selected for each
marine reserve to be similar in location, habitat, and depth to the reserve but
are subject to fishing pressure. 
Not all sites are sampled in each year because of
the gradual implementation of the reserve network and availability of
staff to execute surveys.

A 500 meter square grid overlaid on the area defines the sampling units or
cells. Cells are randomly selected within a marine reserve or comparison area
for each sampling event. Three replicate drifts are executed in each cell.
The specific location of the drifts within the cell is selected by the
captain. Over time, cells without appropriate habitat for the focus species,
mainly groundfish, have been removed from the selection procedures, and
information from all inactive cells is removed from the data prior to any
analyses being conducted.
The number of cells visited in a day ranges from three to five cells.
Data are aggregated to the cell-day.

Of the 940 total cell-days at 14 areas, 626 (66.6\%) of those
had positive `r spp` catches
(Table \@ref(tab:fi-index-ormarres-N)). The number of
`r spp` caught ranged from 0 to 34 fish in a cell-day
(Figure \@ref(fig:fi-index-ormarres-HistogramofPositiveCatchesLing)).
Areas differ in both geographic location and the
level of fishing pressure experienced or allowed. Staff from the Marine
Reserves Program suggested that the treatment (reserve vs. comparison area)
may not be a delineating factor for the catch of `r spp` due to the recent
implementation of the reserves. It was suggested that data could be
aggregated to the site level, functioning at the level of a reef complex, to
examine patterns at different locations along the coast. However, this may
not be possible with the sample size available at some sites.
\Gls{cpue} was calculated using the number of fish per angler hour, where
the number of anglers and hooks are standardized for each survey.
Angler hours have been adjusted for non-fishing time (i.e., travel time, etc.).

Additional filtering may not be necessary, as the filtering for active cells
has already likely removed any unsuitable sampling units, based on habitat,
depth, and local knowledge. Based on the annual proportion of positive
cell-days and the relatively high encounter rate of `r spp` in this survey,
there could be enough data to move forward with a time series at a coastwide
level. Additionally, Redfish Rocks has been sampled yearly since 2011,
except for 2018, making it the best single reserve complex to monitor
inter-annual trends.
\Gls{cpue} at this site shows a relatively stable trend since
2011 for `r spp` (Figure \@ref(fig:fi-index-ormarres-BoxplotLingcodCPUERedfish)).
Coastwide, `r spp` \gls{cpue} appears to be oscillating around
the long-term mean, with the last two years being below average
(Figure \@ref(fig:fi-index-ormarres-RelativemeanLingcodCPUE95CI)).

##### Oregon \glsentrylong{rov} surveys

\gls{odfw} has collected data from \glspl{rov} on `r spp`.
Some of these observations are from \glspl{mpa}.
Unfortunately, these data have not been post processed and
were unavailable for this assessment.

#### \Glsentrylong{wdfw} research compositions

\Gls{wdfw} conducted mark-recapture experiments in the nearshore area at
Cape Flattery from 1986 - 1994.
Though study results were published in several journal articles [@jagielo1990movement].
Additional surveys were conducted in 1997, 2001, 2002, 2003, and 2016 using bottom fish troll gear.
Biological data collected from these surveys were investigated in the previous assessment
but were ultimately removed from the base model because they were not informative
[@haltuch2019lingcod].

#### \Glsentrylong{wdfw} hook and line survey

The \gls{wdfw} hook and line survey started as a pilot study and now includes
more than five years of data.
Unfortunately, the methods have changed over time and the data were not
ready for their inclusion in this assessment.
```

#### \glsentrylong{s-ccfrp}

The \gls{s-ccfrp} is a fishery-independent
hook-and-line survey designed to monitor nearshore fish populations at a series of sampling 
locations both inside and adjacent to \glspl{mpa} along the central California coast
[@Wendt2009; @Starr2015].
The \gls{s-ccfrp} surveys began in 2007 and were originally
designed as a statewide program in collaboration with scientists from \gls{nmfs} and fishermen.
Between 2007-2016 the \gls{s-ccfrp} surveys were focused on the central California coast,
consistently monitoring four \glspl{mpa}.
In 2017, the program was expanded to the coast of California.

The survey design for \gls{s-ccfrp} consists of a number 500 x 500 m cells both within and outside each \gls{mpa}.
On any given survey day, cells are randomly selected within a stratum (inside or outside an \gls{mpa}).
\Glspl{cpfv} are chartered for the survey and the fishing captain is allowed to search within the cell for a fishing location.
During a sampling event, each cell is fished for a total of 30-45 minutes by volunteer anglers.
Each fish encountered is recorded, measured, is linked back to a particular angler, and released (or descended to depth).
Fishing is restricted to shallow depths to avoid barotrauma-induced mortality.
Starting in 2017, a subset of fish have been retained to collect otoliths and fin clips that provide needed biological information for nearshore species.

The index of abundance developed for `r spp` focused drift-level information from the four consistently-sampled \glspl{mpa},
A&ntilde;o Nuevo and Point Lobos, sampled by Moss Landing Marine Labs, and
Point Buchon and Piedras Blancas, sampled by \gls{calpoly}
(Table \@ref(tab:tab-region-ccfrp)).
Therefore, the index, as constructed,
pertains to just the southern stock because the data was collected off of central California
but future work could investigate the utility of generating two indices given
the expansion of the sampling program in 2017.

```{asis, opts.label = 'south', echo = TRUE}
Little filtering of this data set was needed to reduce the number of zeros present in the data set.
Cells not consistently sampled over time were excluded as well as cells that never encountered lingcod.
This filtering led to 6963 retained drifts, with 2814 drifts encountering `r spp`.
Number of retained `r spp` per angler hour was used as the response variable in a Bayesian delta-\gls{glm}
(Tables \@ref(tab:tab-region-ccfrp) and \@ref(tab:tab-year-ccfrp)).
Models with a year and area interaction were not considered in the model selection process.
Trends in the average \gls{cpue} by region were similar (Figure \@ref(fig:fig-areacpue-ccfrp)),
as well as arithmetic mean \gls{cpue} inside and outside \glspl{mpa} over time (Figure \@ref(fig:fig-sitecpue-ccfrp)).

Model selection via differences in \gls{aic} provided support for
year (Table \@ref(tab:tab-year-ccfrp)), site location (Table \@ref(tab:tab-region-ccfrp)), and depth bin (Table \@ref(tab:tab-depth-ccfrp)) as linear predictors for both the
binomial and positive models even though the predictors were not constrained to be the same between the models
(Table \@ref(tab:tab-model-select-ccfrp)).
The binomial model generated data sets with a proportion of zeros similar to the observed 60\%
suggesting the model structure was appropriate for the data.
A Lognormal distribution was supported over a Gamma distribution for the positive model
($\Delta$ \gls{aic} of 322.77; Figure \@ref(fig:fig-dist-fits-ccfrp)).
The estimated index of abundance (Table \@ref(tab:tab-index-ccfrp))
exhibited a trend similar to that of the arithmetic mean of the annual \gls{cpue}
(Figure \@ref(fig:fig-cpue-ccfrp)).
```

#### Rockfish Recruitment and Ecosystem Assessment Survey

<!-- Keeping this in both north and south report because has coastwide elements (BJL) -->
Data on the relative abundance of \gls{yoy} `r spp` are available 
from pelagic midwater trawl surveys that target \gls{yoy} rockfish, other \gls{yoy} groundfish, 
and forage species along the U.S. west coast. The Rockfish Recruitment and 
Ecosystem Assessment Survey has been conducted off central California annually 
between 1983 and 2003 and off most California waters from 2004-2019 
[@adams_RREAsurvey_1993; @sakuma_RREAsurvey_2016],
while the \gls{nwfsc} pre-recruit survey has 
been conducted off the coasts of Oregon and Washington in most years since 2011 
[@brodeur_PRsurvey_2019]. Data from these two surveys are typically combined to 
provide coastwide indices of recruitment for several rockfish stock assessments, 
and as `r spp` are encountered with some frequency, data from these surveys could 
be explored for the development of pre-recruit index for `r spp`.  Some 
additional research and analysis would be necessary to develop this index, 
primarily related to standardizing \gls{yoy} abundance levels to a common age, as is 
done for juvenile rockfish, and evaluating how well past abundance patterns relate 
to assessment year class strength estimates.
