\clearpage
<!--
to do onboarding sa4ss - move this to sa4ss.sty so everyone's figures hold their order
https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr
-->
\floatplacement{table}{H}
# Tables

```{r table-catch, results = "asis"}
sa4ss::read_child(string_switchletter(
  file.path("..", "tables", "table-catchbystate-s-.tex"),
  params$area
))
```

```{r table-management-refpoints, results = "asis"}
management_oflabcacl <- utils::read.csv(file.path("..", "tables", "management-oflabcacl.csv"))
management_oflabcacl %>%
  dplyr::filter(area == params$area) %>%
  dplyr::select(-area) %>%
  dplyr::left_join(
    x = .,
    y = model[["catch"]] %>%
      dplyr::group_by(Yr) %>%
      dplyr::summarize(Observed = sum(Obs, na.rm = TRUE), Expected = sum(kill_bio, na.rm = TRUE), .groups = "keep") %>%
      dplyr::ungroup(),
    by = c(Year = "Yr")
  ) %>%
  dplyr::mutate_at(2:NCOL(.), ~ sprintf("%.2f", .x)) %>%
  kableExtra::kbl(
    longtable = FALSE, booktabs = TRUE, format = "latex",
    caption = paste0(
      "Recent trends in observed landings and expected dead biomass (mt) relative to management guidelines (\\glsentrylong{ofl}, \\glsentryshort{ofl}; \\glsentrylong{abc}, \\glsentryshort{abc}; \\glsentrylong{acl}, \\glsentryshort{acl}). Expected dead biomass represents the total landings plus the model-estimated dead discard biomass.",
      " ", text_wcgop, " ",
      "Additionally, management in 2011 and 2012 was based on a break at 42\\textdegree00\\textquotesingle N versus all other years used \\CapeM."
    ),
    label = "management-refpoints"
  ) %>%
  kableExtra::add_header_above(c(" ", "Management" = 3, "Landings" = 2)) %>%
  kableExtra::kable_styling(latex_options = c("repeat_header"))
```

```{r, cpue-tables, results = "asis", eval = grepl("North", params$area)}
# Arrange figures in order of the time they were modified
tabledataframe <- utils::read.csv(file.path("..", "tables", "tables_cpue.csv"))
tablefiles <- file.path("..", "tables",
  gsub("\\.csv", ".tex", tabledataframe[["filename"]])
)
ignore <- mapply(sa4ss::read_child, tablefiles[grepl("comm", tablefiles)])
ignore <- mapply(sa4ss::read_child, dir_order("..", "tables", grep = "reccpuewa"))
ignore <- mapply(sa4ss::read_child, tablefiles[grepl("rec", tablefiles)])
```
```{asis, opts.label = "north"}
\begin{table}

\caption{\label{tab:tab-year-ORAtSea}Samples by year of lingcod from the  OR At Sea CPFV survey by year.}
\centering
\begin{tabular}[t]{lrrl}
\toprule
Year & Drifts & Positive Drifts & Percent positive\\
\midrule
\cellcolor{gray!6}{2001} & \cellcolor{gray!6}{383} & \cellcolor{gray!6}{179} & \cellcolor{gray!6}{47\%}\\
2003 & 602 & 339 & 56\%\\
\cellcolor{gray!6}{2004} & \cellcolor{gray!6}{424} & \cellcolor{gray!6}{248} & \cellcolor{gray!6}{58\%}\\
2005 & 490 & 237 & 48\%\\
\cellcolor{gray!6}{2006} & \cellcolor{gray!6}{496} & \cellcolor{gray!6}{253} & \cellcolor{gray!6}{51\%}\\
\addlinespace
2007 & 593 & 249 & 42\%\\
\cellcolor{gray!6}{2008} & \cellcolor{gray!6}{539} & \cellcolor{gray!6}{215} & \cellcolor{gray!6}{40\%}\\
2009 & 360 & 145 & 40\%\\
\cellcolor{gray!6}{2010} & \cellcolor{gray!6}{392} & \cellcolor{gray!6}{163} & \cellcolor{gray!6}{42\%}\\
2011 & 361 & 179 & 50\%\\
\addlinespace
\cellcolor{gray!6}{2012} & \cellcolor{gray!6}{618} & \cellcolor{gray!6}{292} & \cellcolor{gray!6}{47\%}\\
2013 & 465 & 245 & 53\%\\
\cellcolor{gray!6}{2014} & \cellcolor{gray!6}{468} & \cellcolor{gray!6}{225} & \cellcolor{gray!6}{48\%}\\
2015 & 403 & 167 & 41\%\\
\cellcolor{gray!6}{2016} & \cellcolor{gray!6}{457} & \cellcolor{gray!6}{196} & \cellcolor{gray!6}{43\%}\\
\addlinespace
2017 & 467 & 190 & 41\%\\
\cellcolor{gray!6}{2018} & \cellcolor{gray!6}{507} & \cellcolor{gray!6}{205} & \cellcolor{gray!6}{40\%}\\
2019 & 447 & 159 & 36\%\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:tab-model-select-ORAtSea}Negative binomial model selection for the OR At Sea CPFV survey index for  lingcod.}
\centering
\begin{tabular}[t]{ll}
\toprule
Model & AIC\\
\midrule
\cellcolor{gray!6}{1} & \cellcolor{gray!6}{19256.43}\\
Year + Port + log(Effort) & 18415.84\\
\cellcolor{gray!6}{Year + Port + Wave + log(Effort)} & \cellcolor{gray!6}{18083.25}\\
Year + Port + Wave + DEPTH bin + log(Effort) & 18037.72\\
\cellcolor{gray!6}{Year + Wave + DEPTH bin + log(Effort)} & \cellcolor{gray!6}{18273.32}\\
\addlinespace
Year + DEPTH bin + log(Effort) & 18576.12\\
\cellcolor{gray!6}{Year + Port + DEPTH bin + log(Effort)} & \cellcolor{gray!6}{18378.51}\\
\bottomrule
\end{tabular}
\end{table}

```

```{r, fi-index-ormarres-tables, results = "asis", eval = grepl("North", params$area)}
xx <- dir(file.path("..", "tables"), pattern = "fi-index-ormarres", full.names= TRUE)
ignore <- mapply(sa4ss::read_child, xx[order(file.info(xx)$mtime)])
```

<!-- Hook and line index -->
```{asis, opts.label = "south"}
\begin{table}
\caption{\label{tab:tab-depth-nwfschl}Positive samples of lingcod in the \glsentrylong{s-hkl} by depth (fm).}
\centering
\begin{tabular}[t]{lrrl}
\toprule
Year & Positive Samples & Samples & Percent Positive\\
\midrule
\cellcolor{gray!6}{(0,50]} & \cellcolor{gray!6}{4} & \cellcolor{gray!6}{207} & \cellcolor{gray!6}{2\%}\\
(50,75] & 86 & 724 & 12\%\\
\cellcolor{gray!6}{(75,100]} & \cellcolor{gray!6}{226} & \cellcolor{gray!6}{2383} & \cellcolor{gray!6}{9\%}\\
(100,125] & 123 & 1620 & 8\%\\
\cellcolor{gray!6}{(125,150]} & \cellcolor{gray!6}{101} & \cellcolor{gray!6}{1121} & \cellcolor{gray!6}{9\%}\\
\addlinespace
(150,175] & 98 & 982 & 10\%\\
\cellcolor{gray!6}{(175,200]} & \cellcolor{gray!6}{20} & \cellcolor{gray!6}{268} & \cellcolor{gray!6}{7\%}\\
(200,230] & 14 & 97 & 14\%\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}
\caption{\label{tab:tab-depthsite-nwfschl}Samples of lingcod in the \glsentrylong{s-hkl} by area and depth bins (ft).}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
Area name & (125,150] & (175,200] & (200,230] & (0,50] & (50,75] & (75,100] & (100,125] & (150,175]\\
\midrule
\cellcolor{gray!6}{Fourteen Mile Bank} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{}\\
107 and 118 Banks &  & 5\% & 0\% &  &  &  &  & \\
\cellcolor{gray!6}{43 Fathom Bank} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{3\%} & \cellcolor{gray!6}{10\%} & \cellcolor{gray!6}{}\\
Anacapa Island & 18\% & 0\% &  &  & 0\% & 4\% & 4\% & 9\%\\
\cellcolor{gray!6}{Catalina Island} & \cellcolor{gray!6}{10\%} & \cellcolor{gray!6}{11\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{11\%}\\
\addlinespace
Central Coast &  &  &  &  &  & 2\% & 0\% & \\
\cellcolor{gray!6}{Cherry Bank} & \cellcolor{gray!6}{10\%} & \cellcolor{gray!6}{5\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{9\%} & \cellcolor{gray!6}{10\%} & \cellcolor{gray!6}{}\\
Cortez Bank & 4\% &  &  & 12\% & 6\% & 5\% & 3\% & 7\%\\
\cellcolor{gray!6}{Garrett Bank} & \cellcolor{gray!6}{6\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{}\\
Harrison Reef & 0\% &  &  &  &  & 2\% & 1\% & \\
\addlinespace
\cellcolor{gray!6}{Hidden Reef} & \cellcolor{gray!6}{25\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{7\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{9\%}\\
Kidney Bank & 11\% &  &  &  &  &  & 12\% & 0\%\\
\cellcolor{gray!6}{Nine Mile Bank} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0\%}\\
Osborn Bank &  &  &  & 0\% & 15\% & 32\% &  & 24\%\\
\cellcolor{gray!6}{Point Conception/Arguello} & \cellcolor{gray!6}{14\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{11\%} & \cellcolor{gray!6}{11\%} & \cellcolor{gray!6}{3\%}\\
\addlinespace
Potato Bank & 4\% &  &  &  &  & 20\% & 8\% & \\
\cellcolor{gray!6}{San Clemente Island} & \cellcolor{gray!6}{8\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{6\%} & \cellcolor{gray!6}{1\%} & \cellcolor{gray!6}{5\%}\\
San Miguel Island & 10\% &  &  &  & 41\% & 22\% & 10\% & \\
\cellcolor{gray!6}{San Nicolas Island East} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{17\%} & \cellcolor{gray!6}{25\%} & \cellcolor{gray!6}{33\%} & \cellcolor{gray!6}{5\%}\\
San Nicolas Island West & 40\% & 0\% &  &  & 5\% & 11\% & 20\% & 5\%\\
\addlinespace
\cellcolor{gray!6}{San Pedro Bay} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{4\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{}\\
Santa Barbara &  &  &  & 1\% & 17\% & 5\% &  & \\
\cellcolor{gray!6}{Santa Barbara Channel} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{2\%} & \cellcolor{gray!6}{13\%}\\
Santa Barbara Island & 8\% & 8\% & 0\% & 4\% & 0\% & 12\% & 15\% & 19\%\\
\cellcolor{gray!6}{Santa Cruz Island} & \cellcolor{gray!6}{33\%} & \cellcolor{gray!6}{15\%} & \cellcolor{gray!6}{20\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{6\%} & \cellcolor{gray!6}{9\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{17\%}\\
\addlinespace
Santa Monica Bay & 1\% &  &  &  &  & 1\% & 0\% & \\
\cellcolor{gray!6}{Santa Rosa Flats} & \cellcolor{gray!6}{11\%} & \cellcolor{gray!6}{6\%} & \cellcolor{gray!6}{15\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{9\%} & \cellcolor{gray!6}{11\%}\\
Santa Rosa Island &  &  &  &  & 18\% & 19\% & 0\% & \\
\cellcolor{gray!6}{Sixty Mile Bank} & \cellcolor{gray!6}{2\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{2\%} & \cellcolor{gray!6}{0\%}\\
South Coast &  &  &  & 0\% & 3\% & 6\% &  & \\
\addlinespace
\cellcolor{gray!6}{Tanner Bank} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{7\%} & \cellcolor{gray!6}{0\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{3\%} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0\%}\\
\bottomrule
\end{tabular}}
\end{table}

\begin{table}
\caption{\label{tab:tab-year-nwfschl}Samples of lingcod in the \glsentrylong{s-hkl} by year.}
\centering
\begin{tabular}[t]{lrrl}
\toprule
Year & Positive Samples & Samples & Percent Positive\\
\midrule
\cellcolor{gray!6}{2004} & \cellcolor{gray!6}{29} & \cellcolor{gray!6}{270} & \cellcolor{gray!6}{11\%}\\
2005 & 27 & 307 & 9\%\\
\cellcolor{gray!6}{2006} & \cellcolor{gray!6}{17} & \cellcolor{gray!6}{303} & \cellcolor{gray!6}{6\%}\\
2007 & 27 & 335 & 8\%\\
\cellcolor{gray!6}{2008} & \cellcolor{gray!6}{11} & \cellcolor{gray!6}{412} & \cellcolor{gray!6}{3\%}\\
\addlinespace
2009 & 16 & 405 & 4\%\\
\cellcolor{gray!6}{2010} & \cellcolor{gray!6}{11} & \cellcolor{gray!6}{414} & \cellcolor{gray!6}{3\%}\\
2011 & 30 & 393 & 8\%\\
\cellcolor{gray!6}{2012} & \cellcolor{gray!6}{53} & \cellcolor{gray!6}{414} & \cellcolor{gray!6}{13\%}\\
2013 & 62 & 409 & 15\%\\
\addlinespace
\cellcolor{gray!6}{2014} & \cellcolor{gray!6}{67} & \cellcolor{gray!6}{530} & \cellcolor{gray!6}{13\%}\\
2015 & 75 & 615 & 12\%\\
\cellcolor{gray!6}{2016} & \cellcolor{gray!6}{77} & \cellcolor{gray!6}{623} & \cellcolor{gray!6}{12\%}\\
2017 & 69 & 652 & 11\%\\
\cellcolor{gray!6}{2018} & \cellcolor{gray!6}{64} & \cellcolor{gray!6}{660} & \cellcolor{gray!6}{10\%}\\
\addlinespace
2019 & 37 & 660 & 6\%\\
\bottomrule
\end{tabular}
\end{table}
```


<!-- Sample size tables -->
```{r, comp-sample-size-tables, results = "asis"}

sa4ss::read_child(filein = file.path("..", "tables", paste0("length_samps_", params$area, ".tex")))

sa4ss::read_child(filein = file.path("..", "tables", paste0("age_samps_", params$area, ".tex")))
```

<!-- Sample size tables for commercial by state -->
```{r, comp-sample-size-tables-commbyState, results = "asis", eval = grepl("North", params$area)}

sa4ss::read_child(filein = file.path("..", "tables", paste0("length_samps_comm_byState_", params$area, ".tex")))

sa4ss::read_child(filein = file.path("..", "tables", paste0("age_samps_comm_byState_", params$area, ".tex")))
```


<!-- ====================================================================== -->
<!-- 30model tables -->
<!-- ====================================================================== -->
```{r tables-model, results = "asis"}
table_outputconfig(model)
cat("\\begin{landscape}")
table_pars(model)
cat("\\end{landscape}")
table_likelihoods(model)
table_dq(model)
table_ts(model)
table_compweight(model)
```

<!-- ====================================================================== -->
<!-- 30model sensitivity tables -->
<!-- ====================================================================== -->
\begin{landscape}
```{r tables-model-sens, results = "asis"}
table_sens(string_switchletter("../tables/sens_table_s_bio_rec.csv", params$area))
table_sens(string_switchletter("../tables/sens_table_s_index.csv", params$area))
table_sens(string_switchletter("../tables/sens_table_s_comp.csv", params$area),
caption = "Differences in likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns). Red values indicate negative log likelihoods that were lower than that for the base model. Each column refers to index data that were taken out of the model.")
table_sens("../tables/table_compare_north_vs_south.csv")
```
\end{landscape}
