\clearpage
<!--
to do onboarding sa4ss - move this to sa4ss.sty so everyone's figures hold their order
https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr
-->
\floatplacement{figure}{H}
# Figures

```{r, results = "asis"}
do.call(
  sa4ss::add_figure,
  utils::read.csv(file.path("..", "figures", "map_of_stock_boundaries_40-10.csv"))
)
```

```{r, results = "asis"}
sa4ss::add_figure(
  filein = file.path(params$model, "plots", "data_plot.png"),
  caption = "Summary of data sources used in the base model",
  alt_caption = "Dots for each year a source of data is available",
  label = "data-plot"
)
```

```{r, catch-figures, results = "asis"}
# Arrange figures in order of the time they were modified
figdataframe <- dplyr::bind_rows(mapply(
  FUN = utils::read.csv,
  file = dir(file.path("..","figures"), pattern = "^catch-.+\\.csv",full.names=TRUE),
  SIMPLIFY = FALSE
))
figdataframe[, "time"] <- file.info(figdataframe[["filein"]])[["mtime"]]
ignore <- apply(
  figdataframe %>% dplyr::arrange(time) %>% dplyr::select(-time),
  1,
  function(x) do.call(sa4ss::add_figure, args = as.list(x))
)
```

```{r, cpue-figures, results = "asis"}
# Use figures-cpue.csv to bring in ordered set of figures
ignore <- apply(
  utils::read.csv(file.path("..", "figures", "figures_cpue.csv")),
  1,
  function(x) do.call(sa4ss::add_figure, args = as.list(x))
)
```


<!-- ====================================================================== -->
<!-- ******************     20Data figures     **************************** --> 
<!-- ====================================================================== -->

<!-- WCGBTS -->

```{r, echo=FALSE, results='asis'}
nm = "WCGBTS_presence_absence_by_depth_bin.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Presence/absence of ", spp, " in the WCGBTS by 25 m depth increments"),
label = 'wcgbts-presAbs')
```

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "WCGBTS - North _Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the WCGBTS"),
label = 'wcgbts-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "WCGBTS - South _Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the WCGBTS"),
label = 'wcgbts-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "WCGBTS - North _Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the WCGBTS"),
label = 'wcgbts-ageComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "WCGBTS - South _Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the WCGBTS"),
label = 'wcgbts-ageComp')
```


<!-- Triennial -->

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Triennial_cpueXdepth.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Raw catch per unit effort in positive tows by depth in
                 the triennial survey"),
label = 'tri-depthSplit')
```

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "Triennial - North _Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the Triennial survey"),
label = 'tri-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Triennial - South _Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the Triennial survey"),
label = 'tri-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "Triennial - North _Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the Triennial survey"),
label = 'tri-ageComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Triennial - South _Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = paste0("Length frequency for male and females in the Triennial survey"),
label = 'tri-ageComp')
```


<!-- Hook and Line -->

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "HNL lengths Male-Female_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length frequency for male and females in the Hook and Line survey",
label = 'hkl-lenComp-sexed')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "HNL lengths Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length frequency for unsexed fish in the Hook and Line survey",
label = 'hkl-lenComp-unsexed')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Hook and Line_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age frequency for male and females in the Hook and Line survey",
label = 'hkl-ageComp')
```


<!-- Lam research -->

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "Lam Thesis lengths Male-Female North_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length frequency for male and females from Lam research data",
label = 'lam-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Lam Thesis lengths Male-Female South_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length frequency for male and females from Lam research data",
label = 'lam-lenComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "Lam Thesis ages Male-Female South_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age frequency for male and females from Lam research data",
label = 'lam-ageComp')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Lam Thesis ages Male-Female South_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age frequency for male and females from Lam research data",
label = 'lam-ageComp')
```


<!-- ====================================================================== -->
<!-- ******************     Biology Figures     **************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis', opts.label = 'north'}
nm = "Length_Weight_Combo_North.png"
sa4ss::add_figure(
filein = file.path("..", "figures", "biology_exploration", nm),
caption = "Weight-length relationship for males and females from the WCGBTS",
label = 'len-weight')
```

```{r, echo=FALSE, results='asis', opts.label = 'south'}
nm = "Length_Weight_Combo_South.png"
sa4ss::add_figure(
filein = file.path("..", "figures", "biology_exploration", nm),
caption = "Weight-length relationship for males and females from the WCGBTS",
label = 'len-weight')
```


<!-- ====================================================================== -->
<!-- ******************     Recreational Length and Age Comps    ********** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis', opts.label = 'north'}
##
#Lenghts
##

nm = "WA Recreational - Sexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the Washington recreational fleet for males and females",
label = 'wa-lencomp-sexed')

nm = "WA Recreational - Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the Washington recreational fleet for unsexed fish",
label = 'wa-lencomp-unsexed')


nm = "OR Recreational - Sexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the Oregon recreational fleet for males and females",
label = 'or-lencomp-sexed')

nm = "OR Recreational - Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the Oregon recreational fleet for unsexed fish",
label = 'or-lencomp-unsexed')


nm = "CA North Recreational - Sexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the California recreational fleet north of 40 degrees 10 minuts N lattidue for males and females",
label = 'ca-lencomp-sexed')

nm = "CA North Recreational - Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the California recreational fleet north of 40 degrees 10 minuts N lattidue for unsexed fish",
label = 'ca-lencomp-unsexed')


##
#Ages
##

nm = "WA Recreational - Sexed_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age distributions for the Washington recreational fleet for males and females",
label = 'wa-agecomp-sexed')

nm = "WA Recreational - Unsexed_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age distributions for the Washington recreational fleet for unsexed fish",
label = 'wa-agecomp-unsexed')

nm = "OR Recreational - Sexed_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age distributions for the Oregon recreational fleet for males and females",
label = 'or-agecomp-sexed')

nm = "OR Recreational - Unsexed_Age_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Age distributions for the Oregon recreational fleet for unsexed fish",
label = 'or-agecomp-unsexed')
```



```{r, echo=FALSE, results='asis', opts.label = 'south'}
##
#Lengths
##
nm = "CA South Recreational - Sexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the California recreational fleet south of 40 degrees 10 minuts N lattidue for males and females",
label = 'ca-lencomp-sexed')

nm = "CA South Recreational - Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the California recreational fleet south of 40 degrees 10 minuts N lattidue for unsexed fish",
label = 'ca-lencomp-unsexed')

nm = "debHist - Unsexed_Length_Frequency.png"
sa4ss::add_figure(
filein = file.path("..", "figures", nm),
caption = "Length distributions for the historical onbaord sampling of party boats from 1987-1998. Fish were not sexed from this dataset",
label = 'debWV-lencomp-unsexed')



```

