```{r catch-figures-make}

gg <- ggplot2::ggplot(
  catch_comm_state,
  ggplot2::aes(Year, mt, lty = source, pch = fleet, col = fleet)
) +
  ggplot2::geom_line() +
  # ggplot2::geom_point() +
  ggplot2::geom_line(ggplot2::aes(y = catch)) +
  # ggplot2::geom_point(aes(y = catch)) +
  ggplot2::facet_grid(state ~ .) +
  ggplot2::theme_bw() +
  ggplot2::theme(strip.background = ggplot2::element_rect(fill = NA)) +
  ggplot2::theme(legend.position = c(0.1, 0.8)) +
  ggplot2::ylab("Landings (mt)") +
  ggplot2::scale_color_manual(
    values = unlist(t(get_fleet(value="Comm")[,c("col.n")]),use.names=FALSE)
  )
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-state.png"),
  caption = paste0(
    "Comparison of commercial catch time series from this model ",
    "(dashed line) and the previous assessment model (solid line). ",
    "Fixed gear (FG; dark blue) and trawl (TW; light blue) ",
    "are shown for both the northern (top panel; Oregon and Washington) and ",
    "southern (bottom panel; California) as defined in the previous assessment model."
  ),
  alttext = paste(
    "Time series of commercial catches are less in the early years for the new southern model than the previous assessment."
  )
)

gg <- ggplot2::ggplot(catch_comm_CA_interpolate,
  ggplot2::aes(
    x = Year,
    y = mt_orig,
    col = interaction(area, fleet, sep = " - "),
  )
) +
  ggplot2::geom_line() +
  ggplot2::geom_line(ggplot2::aes(y = mt), lty = 2) +
  ggplot2::geom_point(cex = 2) +
  ggplot2::ylab("Commercial landings (mt)") +
  ggplot2::guides(
    colour = ggplot2::guide_legend(title = "area x fleet")
  ) +
  ggplot2::scale_colour_manual(
    values = unlist(t(get_fleet(value="Comm")[,c("col.n","col.s")]),use.names=FALSE)
  ) +
  ggplot2::theme_bw() + ggplot2::theme(legend.position = c(0.1, 0.8))
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-CA-interpolate-ts.png"),
  caption = paste0(
    "Reconstructed commercial landings for the state of California by fleet ",
    "(fixed gear, FG, circles; trawl gear, TW, triangles) and ", 
    "area (northern region, blue; southern region, red). ",
    "Dashed line indicates data were interpolated across years."
  ),
  alttext = paste(
    ""
  )
)

gg <- catch_comm_CA_ralston %>%
  dplyr::group_by(Year, area, state) %>%
  dplyr::summarize(mt = sum(mt), .groups = "keep") %>%
  dplyr::ungroup() %>%
  dplyr::group_by(Year, state) %>%
  dplyr::mutate(prop = mt / sum(mt)) %>%
  dplyr::full_join(
    by = c("Year", "area"),
    x = .,
    y = catch_comm_CA_MM
  ) %>% data.frame %>%
  dplyr::filter(type == "ALL" & area == "North") %>%
ggplot2::ggplot(
  size = 2,
  ggplot2::aes(x = Year, y = prop)
) +
  ggplot2::geom_point(pch = 1) +
  ggplot2::geom_point(ggplot2::aes(y = prop_fa)) +
  ggplot2::ylim(c(0, 1.0)) +
  ggplot2::theme_bw() +
  ggplot2::ylab("Proportion of CA commercial catch in the northern area")
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-CA-proportionnorth.png"),
  caption = paste0(
    "Yearly proportion of California (CA) commercial catch landed in the ",
    "the northern region (i.e., north of ",
    "forty degrees ten minutes latitude", ") ",
    "of all CA commercial catches from two data sources, ",
    "the Raltson et al. (2010) catch reconstruction effort (open circles) and ",
    "fish ticket data in CALCOM, the database used by the ",
    "California Cooperative Groundfish Survey to store and manage ",
    "commercial market sample data, (filled circles)."
  ),
  alttext = paste0(
    "Proportions largely agree between both data sets."
  ),
  label = "catch-comm-CA-proportionnorth"
)

gg <- ggplot2::ggplot(data = catch_comm_pacfin %>%
  dplyr::filter(Year < as.numeric(format(Sys.Date(), "%Y"))) %>%
  dplyr::group_by(Year, area, fleet) %>%
  dplyr::summarize(MT = sum(ROUND_WEIGHT_MTONS), .groups = "keep")) +
  ggplot2::geom_bar(stat="identity", lwd = 0.2,
    ggplot2::aes(
      x = Year,
      y = MT,
      fill = interaction(area, fleet, sep = " ")
    )
  ) +
  ggplot2::scale_fill_manual(
    values  = unlist(t(get_fleet(value="Comm")[,c("col.n","col.s")]),use.names=FALSE)
  ) +
  ggplot2::facet_grid(area ~ .) +
  ggplot2::xlab("Year") + ggplot2::ylab("Landings (mt)") +
  ggplot2::labs(fill = ggplot2::guide_legend(title = "area x fleet")) +
  ggplot2::theme_bw() + ggplot2::theme(
    strip.background = ggplot2::element_rect(fill = NA),
    text = ggplot2::element_text(size = 16)
    )
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-ts-pacfin.png"),
  caption = paste0(
    "Yearly commercial landings (mt) from the PacFIN database since 1981 ",
    " by area (panel and color) and fleet (shading). ",
    "Trawl gear (TW) includes all trawl, nets, and dredging. ",
    "Fixed gear (FG) includes all other gear types."
  ),
  alttext = paste(
    ""
  )
)

gg <- catch_comm_pacfin %>%
  dplyr::filter(AGENCY_CODE == "C", Year != as.numeric(format(Sys.Date(), "%Y"))) %>%
  dplyr::mutate(gear = factor(fleet)) %>%
  dplyr::group_by(Year, fleet, area)  %>%
  dplyr::summarize(mt = sum(ROUND_WEIGHT_MTONS), .groups = "keep") %>%
  dplyr::group_by(Year, fleet) %>%
  dplyr::mutate(percentage = mt/sum(mt)) %>%
  ggplot2::ggplot(ggplot2::aes(
    x = Year,
    y = percentage,
    fill = interaction(area, fleet)
  )) +
  ggplot2::scale_fill_manual(
    values = unlist(t(get_fleet(value="Comm")[,c("col.n","col.s")]),use.names=FALSE)
  ) +
  ggplot2::facet_grid(fleet ~ .) +
  ggplot2::geom_bar(position = "stack", stat = "identity") +
  ggplot2::scale_y_continuous(labels = scales::percent) +
  ggplot2::theme_bw() + ggplot2::theme(
    strip.background = ggplot2::element_rect(fill = NA),
    # text = ggplot2::element_text(size = 10),
    legend.position = "none"
  ) +
  ggplot2::xlab("Year") + ggplot2::ylab("California commercial catch by area")
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-CA-gearprop.png"),
  caption = paste0(
    "Percentage of California commercial catch by area within each fleet ",
    "(fixed gear, FG, upper panel; trawl, TW, lower panel)",
    "since 1981. ",
    "Darker shades represent the northern area and lighter shades represent the southern area."
  ),
  alttext = paste(
    ""
  )
)

gg <- bio_rec_recfin %>%
  dplyr::group_by(Year, STATE_NAME, AGENCY_WEIGHT_UNITS, IS_RETAINED, sex) %>%
  dplyr::summarize(.groups = "keep",
    mean = mean(RECFIN_LENGTH_MM, na.rm = TRUE)
  ) %>%
  ggplot2::ggplot(ggplot2::aes(Year, mean, col = STATE_NAME, lty = STATE_NAME)) +
  ggplot2::geom_point(cex = 5, alpha = 0.5) +
  ggplot2::geom_smooth(method = "lm", se = FALSE) +
  ggplot2::scale_color_manual(
    values = get_fleet(value="rec")[,c("col.n")]
  ) +
  ggplot2::ylab("Mean length (mm)") +
  ggplot2::labs(col = "", lty = "") +
  ggplot2::theme_bw() +
  ggplot2::theme(
    legend.position = c(0.15, 0.90),
    strip.background = ggplot2::element_rect(fill = NA)
  ) +
  ggplot2::facet_grid(tolower(IS_RETAINED) ~ factor(sex, labels = c("female", "male", "unknown sex")))
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-rec-tsrecfinmeanlength.png"),
  caption = paste0(
    "Mean length (mm) of released (top) and retained (bottom) fish from the ",
    "recreational fishery for Washington (squares and dashed line), ",
    "Oregon (triangles and dash-dot line), and California (circles and solid line) ",
    " by sex (columns). ",
    "The average of retained fish across all years was used to translate ",
    "numbers to weight for Washington."
  ),
  alttext = paste(
    ""
  )
)

gg <- ggplot2::ggplot(
  catch_rec %>%
    dplyr::group_by(Year, state) %>%
    dplyr::summarize(mt = sum(mt), .groups = "keep") %>%
    dplyr::ungroup(),
    ggplot2::aes(Year, mt)
  ) +
  ggplot2::geom_line(ggplot2::aes(col = state), lty = 2) +
  ggplot2::scale_color_manual(
    values = rev(get_fleet(value="rec")[,c("col.n")])
  ) +
  ggplot2::geom_line(
    lty = 1,
    col = get_fleet(value="CA")[,c("col.n")],
    data = last_ssdat[[2]][["catch"]] %>%
      dplyr::filter(fleet == grep("REC", last_ssdat[[2]][["fleetnames"]]), catch > 0),
    ggplot2::aes(year, catch)
  ) +
  ggplot2::geom_line(
    lty = 1,
    col = get_fleet(value="OR")[,c("col.n")],
    data = last_ssdat[[1]][["catch"]] %>%
      dplyr::filter(fleet == grep("OR", last_ssdat[[1]][["fleetnames"]]), catch > 0),
    ggplot2::aes(year, catch)
  ) +
  ggplot2::geom_line(
    lty = 1,
    col = get_fleet(value="WA")[,c("col.n")],
    data = last_ssdat[[1]][["catch"]] %>%
      dplyr::filter(fleet == grep("WA", last_ssdat[[1]][["fleetnames"]]), catch > 0),
    ggplot2::aes(year, catch)
  ) +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position = c(0.1, 0.8)) +
  ggplot2::ylab("Recreational landings (mt)")
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-rec-ca-oldts.png"),
  caption = paste0(
    "Comparison of recreational landings from this assessment (dashed line) versus ",
    "the previous assessment (solid line) for each state (colors)."
  ),
  alttext = paste(
    ""
  )
)

gg <- ggplot2::ggplot(
  catch_rec_CA,
  ggplot2::aes(Year, mt, col = area)
) +
  ggplot2::geom_point(ggplot2::aes(pch = source)) +
  ggplot2::geom_line() +
  ggplot2::scale_colour_manual(
    values = unlist(use.names = FALSE, get_fleet("CA", col = c("col.n", "col.s")))
  ) +
  ggplot2::theme_bw() +
  ggplot2::ylab("Recreational California landings (mt)")
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-rec-CA-ts.png"),
  caption = paste0(
    "Time series of California recreational landings (mt) for the ",
    "northern (darker color) and southern (lighter color) areas. ",
    "The shape of the points indicates the information source ",
    "(California Recreational Fisheries Survey, CRFS; linear interpolation, interpolate; ",
    "Marine Recreational Fisheries Statistics Survey, MRFSS; ",
    "old Stock Synthesis, SS, model)."
  ),
  alttext = paste(
    ""
  )
)

gg <- ggplot2::ggplot(
  catch_rec,
  ggplot2::aes(Year, mt, col = interaction(area, state, sep = " "))
) +
  ggplot2::geom_line(size=1.2) +
  ggplot2::scale_color_manual(
    values = unlist(use.names = FALSE, get_fleet(value="rec")[c(3,3,2,1), c("col.n", "col.s")])[c(1,5,3,4)]
  ) +
  ggplot2::labs(col = "fleet") +
  ggplot2::ylab("Recreational landings (mt)") +
  ggplot2::theme_bw()
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-rec-ts.png"),
  caption = paste0(
    "Time series of recreational landings by state and area."
  ),
  alttext = paste(
    ""
  )
)
```

```{r catch-comm-seasonality, eval = FALSE, fig.cap = ""}
gg <- ggplot2::ggplot(data = catch_comm_pacfin %>%
  dplyr::group_by(Year, LANDING_MONTH, area, fleet) %>%
  dplyr::summarize(.groups = "keep",
    MT = sum(ROUND_WEIGHT_MTONS),
    n = length(unique(VESSEL_ID))) %>%
  dplyr::mutate(fleet = ifelse(fleet == "FG", "Fixed gear", "Trawl")) %>%
  dplyr::ungroup() %>%
  dplyr::filter(n > 3),
  ggplot2::aes(y = MT, x = LANDING_MONTH, col = Year)) +
  ggplot2::xlab("") + ggplot2::ylab("Commercial landings (mt; log scale)") +
  ggplot2::geom_point(size=4, alpha = 0.3) +
  ggplot2::guides(alpha = "none") +
  ggplot2::theme_bw() + ggplot2::theme(
    legend.position = "bottom",
    legend.key.width = grid::unit(3, "cm"),
    strip.background = ggplot2::element_rect(fill = NA),
    text = ggplot2::element_text(size = 16)
    ) +
  ggplot2::labs(colour = ggplot2::guide_legend(title = "Year")) +
  ggplot2::coord_polar() +
  ggplot2::facet_grid(fleet~area) +
  ggplot2::scale_colour_viridis_c(direction = -1) +
  ggplot2::scale_x_continuous(
    limits = c(0, 12), expand = c(0, 0),
    breaks = seq(1, 12, by = 1),
    labels = c("Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug",
      "Sep", "Oct", "Nov", "Dec")) +
  ggplot2::scale_y_continuous(trans = "log", breaks = c(0, 1, 10, 100, 1000))
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-seasonality.png"),
  caption = paste0(
    "Exploratory figure, not ready for production. ",
    "Seasonality (month; x axis) of landings (mt) by area (column) and fleet (row). ",
    "The y axis is on the log scale, colors represent years, and ",
    "circles are transparent to facilitate visualization of months with many records."
  ),
  alttext = paste(
    ""
  )
)


gg <- ggplot2::ggplot(
  catch_comm,
  ggplot2::aes(Year, mt, col = interaction(area, fleet, sep = " "))
) +
  ggplot2::geom_line(size = 1.2) +
  ggplot2::scale_colour_manual(
    values = unlist(t(get_fleet(value="Comm")[,c("col.n","col.s")]),use.names=FALSE)
  ) +
  ggplot2::labs(ylab = "Landings (mt)", colour = ggplot2::guide_legend(title = "area x fleet")) +
  ggplot2::theme_bw()
ggsave2(
  gg,
  filename = file.path("..", "figures", "catch-comm-ts-full.png"),
  caption = paste0(
    "Commercial landings (mt) by year (x axis), area, and fleet, ",
    "with darker colors representing catch from the northern area and ",
    "lighter colors from the southern area."
  ),
  alttext = paste(
    "Recent landings are much smaller than pre-2000 landings for all commercial fleets."
  )
)
```
