## Basic Information

This assessment applies to Lingcod (Ophiodon elongatus) off the West Coast of the United States, and is conducted as independent stock assessment models, divided at Cape Mendocino. This is the same approach implemented in recent Lingcod assessments, however the division of the two stocks has moved from the previous line at the California-Oregon border ($42^\circ$ North Latitude) to Cape Mendocino $40^\circ 10^\prime$ due to new information about genetic variation within the stock.

Until recently, Lingcod were believed to be genetically similar across their range with little stock connectivity at moderate (~10 km) to large (~1000 km) scales [@marko2007mtdna].  Newly published work shows that there are genetic differences between the northern and southern stocks, and that the waters from $35^\circ$ N to $43^\circ$ N constitute an area of overlap between the two [@longo2020strong].

Through 2010, the stock was managed as a coast-wide population.  In 2011 and 2012 Lingcod were managed as two stocks with a break at the California-Oregon border ($42^\circ$ N).  In 2013 the management line for commercial catch was established at $40^\circ 10^\prime$ N, near Cape Mendocino.  This line is within the area of mixing between the northern and southern stocks; it was selected as the delineation point between the two stocks for this assessment.

Three fisheries are modeled in the north: commercial trawl (including limited landings in other net gears), commercial fixed gears (including all line gears), and recreational fisheries. Three fisheries are modeled in the south: commercial trawl (including limited landings in other net gears), commercial fixed gears (including all line gears), and southern CA recreational fisheries. Both models begin in 1889, at the onset of landings.

## Life History

*Geography*  
Lingcod (Ophiodon elongatus, family Hexagrammidae), are large, opportunistic predators endemic to the North Pacific, ranging from the Gulf of Alaska to central Baja California, Mexico [@wilby1937ling; @hart1973pacific].  The historic center of abundance is off British Columbia and Washington State [@hart1973pacific].  While Lingcod are caught in the West Coast Bottom Trawl Survey to depths of 450 m, they more typically occur at depths less than 200 m.  Lingcod are demersal on the continental shelf, display a patchy distribution, and are most abundant in areas of hard bottom with rocky relief [@rickey1991geographical].  

*Size, growth, and maturity*  
Lingcod are sexually dimorphic, with females typically growing faster and attaining larger asymptotic sizes than males [@richards1990multivariate]. Females also reach maturity at larger sizes [@cass1990lingcod; @miller1973fish].  Lingcod exhibit a latitudinal trend in growth, longevity, and size at maturity, such that individuals from northern waters generally grow faster, live longer, and mature at larger sizes than individuals from southern regions [@richards1990multivariate; @silberberg2001analysis; @lam2019geographic].

*Spawning*  
Lingcod are iteroparous spawners.  Male Lingcod first aggregate in late fall and move to rocky habitat in shallower water (intertidal to 126 m [@giorgi1981environmental; @o1993submersible], where they guard areas suitable for spawning.  This movement is correlated with a decline in the proportion of males in offshore trawl landings in late fall [@miller1973fish (California); @cass1990lingcod (British Columbia); @jagielo1994assessment (Washington)]. Mature females are rarely seen on the spawning grounds and appear to move from deepwater habitats into spawning areas only for a brief period to deposit eggs [@giorgi1981environmental]. Larger and older females appear to spawn first [@cass1990lingcod], depositing up to 500,000 eggs in high current areas [@hart1973pacific; @low1978study].  After fertilization, males guard clutches until the eggs hatch in six to eight weeks [@king2005male; @withler2004polygamous], between January and June [@jewell1968scuba; @low1978study]. Recent maturity studies suggest that Lingcod are batch spawners with ability to spawn year round, with peak spawning taking place during October through December (pers. comm, Melissa Head, NWFSC).

*Larvae*  
At hatching, Lingcod larvae are about 12 mm in total length and are epipelagic for about 90 days, until reaching about 70 mm and settling to soft bottom habitats [@phillips1977early; @cass1990lingcod; @hart1973pacific).   Epipelagic larvae feed on small copepods and copepod eggs, shifting to larger copepods and fish larvae as they grow [@phillips1977early].  Young-of-the-year (YOY) typically recruit to sandy, low relief habitat near eelgrass or kelp beds, staying on soft bottom until they grow to at least 350 mm in length, when they move into rocky, high relief substrate, which is the preferred adult habitat [@petrie2006hunger; @bassett2018lingcod]. 

*Juveniles*  
Newly settled juveniles have been sampled nearshore in June on sandy bottom areas [@buckley1984enhancement], and have been found at depths ranging from 9-55 m  [@phillips1977early; @miller1973fish; @coley1986juvenile]. In Washington, juveniles have been collected from the mouth of the Pysht River in the Strait of Juan de Fuca, from Grays Harbor and Willapa Bay, and from coastal waters nearshore to these embayments [@buckley1984enhancement; @jagielo1994assessment]. Coley et al. [-@coley1986juvenile] found juvenile Lingcod in Grays Harbor in October, over hard bottom shell-cobble habitat near rocks in 9-15 m of water.  Surveys off the west coast of Vancouver Island suggest that juveniles move from inshore areas to a wider range of flat bottom areas by September [@cass1990lingcod], and begin to move into habitats of similar relief and substrate as adult Lingcod by age two, but remain at shallower depths. An analysis of juvenile Lingcod distribution on the U.S. West Coast [@tolimieri2020SpatioTemporal] found a  large hotspot in central California shelf waters (50-240 m) between $34^\circ$ N and $39^\circ$ N with smaller hotspots around $41^\circ$ N and $43^\circ$ N (just north of Cape Mendocino and Cape Blanco). This found higher juvenile density in the south than in the north, but noted that the observations were from the WCGBT Survey which has an inshore limit of 55 m. Therefore differences in juvenile depth distribution between north and south may have influenced the results.

*Juvenile diet and growth*  
Juvenile Lingcod feed on small fishes including Pacific Herring (*Clupea pallasii*), Pacific Sand Lance (*Ammodytes hexapterus*), flatfishes (*Pleuronectidae*), Shiner Perch (*Cymatogaster aggregate*), and Walleye Pollock (*Theragra chalcograma*), and an assortment of invertebrates including shrimps (Neomysis) and prawns (Pandalus) [@cass1990lingcod]. As juvenile Lingcod begin to move into rocky habitats and exceed 30 cm, other rocky reef bottomfishes  become a more prominent component of their diet, making up 48.8% of total prey biomass by weight [@beaudreau2007spatial].  Phillips and Barraclough [-@phillips1977early] estimated that YOY growth was approximately 1.3 mm/day. Buckley et al. [-@buckley1984enhancement] reported YOY growth from June to September in the Strait of Juan de Fuca also averaged 1.3mm/day. Samples from the mouth of the Pysht River averaged 96 mm in June, 135 mm in July, 173 mm in August and 200 mm in September [@jagielo1994assessment].

*Habitat use*  
Outside of spawning season, male and female Lingcod are segregated by depth where females tend to inhabit deeper offshore waters and males inhabit nearshore rocky reefs. Consequently, each sex is vulnerable to different types of fishing gear. The majority of nearshore males (66.3%) are caught using hook-and-line or spearfishing gear, and a majority of deep water females (62.4%) are caught by trawl gear [@miller1973fish]. Miller and Geibel [-@miller1973fish] reported that juvenile Lingcod in California are about 35 cm in length (1 year old) when they first move into nearshore rocky areas typical of adult habitat. Fishery and survey data indicate that male Lingcod tend to be more abundant than females in shallow waters, and the size of both sexes increase with depth [@jagielo1994assessment].

*Movement*  
The movement and migration of Lingcod has been extensively studied through tag-recapture methods and acoustic arrays. As adults, Lingcod have a high degree of site fidelity and tend to stay within an 8 km home range. Cass et al. [-@cass1990lingcod] found that 95% of fish recovered from a tagging study off the west coast of Vancouver Island were recaptured near the point of release.  In Cape Flattery, Washington, Jagielo [-@jagielo1990movement] reported that 80.7% of tagged fish were recovered <8 km from their original release site.  U.S. and Canadian tagging studies have demonstrated movement between coastal areas off Washington and southwest Vancouver Island. However, there is little interchange between these areas and the inland marine waters of Puget Sound and the Strait of Georgia [@cass1990lingcod; @jagielo1990movement].

Most fish recovered in tagging studies are found near the point of release, but some exceptional movements have been reported.  In Jagielo's Cape Flattery study, [-@jagielo1990movement] only 19.3% of recoveries were further than 10 km from the release point.  However, fish were recaptured as far north as Queen Charlotte sound (195 km) and as far south as Cape Falcon (120 km).  One fish tagged as a juvenile was recovered 510 km to the south in Oregon [@jagielo1990movement]. 

Starr et al. [-@starr2005use] in Alaska, and Greenley [-@greenley2009movements], in Central California used acoustic tags for tracking Lingcod movement and both observed that while Lingcod exhibit high site fidelity with an established location of residence, they frequently leave for brief periods of time (1-5 days) over short distances (2 km) to feed, then return home for a longer duration. Large females generally had shorter residency times, spending more time outside of their tagged site. Additional acoustic studies by Bishop et al. [-@bishop2010situ] and Stahl et al. [-@stahl2014examinationof] in Prince William Sound have reported that younger individuals (2-4 year olds, around 50 cm) disperse from nearshore reefs during spawning season, most likely due to displacement by older and larger spawning individuals. Overall, residency times varied by sex, size, season, and habitat of residence.

*Diet and trophic ecology*    
Lingcod are top order predators of the family Hexagrammidae. Among the Hexagrammidae, the genus *Ophiodon* is ecologically intermediate between the more littoral genera *Hexagrammos* and *Oxylebius*; and the more pelagic *Pleurogrammus* [@rutenberg1962system]. Lingcod are opportunistic predators, feeding on a variety of fishes (pelagic and demersal), cephalopods, and crustaceans [@wilby1937ling].  Rockfish biomass in the Lingcod diet increases by three-fold for Lingcod found inside marine reserves [@beaudreau2007spatial]. 

A recent coastwide diet study showed that Lingcod consumed a wide variety of prey and exhibited both generalist and opportunist feeding strategies that varied with depth of occurrence, latitude, sex, and size (B. Brown, Moss Landing Marine Laboratories, personal communication, 31 March 2021). Male Lingcod caught in shallow depths consumed more lower trophic level prey items (e.g. cephalopods) and had more diverse diets, while female Lingcod caught in deep depths consumed more higher trophic level prey items (e.g. groundfishes) and had less diverse diets. Geographic variation in trophic level was associated with oceanographic factors such as sea-surface temperature or chlorophyll a density that likely corresponds to shifts in prey availability, suggesting a similar shift in the predatory role of Lingcod in coastal environments (B. Brown, Moss Landing Marine Laboratories, personal communication, 31 March 2021). 

Preliminary observations (B. Brown, Moss Landing Marine Laboratories, personal communication, 6 April 2017) from Lingcod stomach contents sampled from Washington to California in both nearshore and offshore habitats indicate a higher occurrence of bony fishes from Washington and Oregon waters, and a higher occurrence of cephalopods in Lingcod from California waters with an overlapping region near southern Oregon. This latitudinal shift in prey composition suggests differences in feeding behavior and in the predatory role of Lingcod in coastal environments.

*Stock delineation*    
A number of Lingcod studies have been conducted since the last assessment and contribute to current understanding of how the West Coast Lingcod stock can be delineated using genetic and life-history-based evidence. Contrary to previous genetics work using mitochondrial DNA that found no genetic differentiation in the Lingcod population [@marko2007mtdna], Longo, et al. [-@longo2020strong] used restriction site-associated DNA sequencing (RADseq) techniques and discovered evidence for distinct north and south genetic clusters with the presence of admixed individuals in the region of overlap. The pure northern cluster individuals represented over 80% of the samples at $42.2^\circ$ N and further north while the pure southern individuals were over 80% at $35.2^\circ$ N and further south. The admixed individuals represented a plurality of samples at two sites near the center of this range, at $38.6^\circ$N and $39.5^\circ$ N.  
       
A recent life-history study on U.S. West Coast Lingcod demonstrates that Lingcod growth, longevity, and timing at maturity exhibit a latitudinal gradient, where Lingcod from higher latitudes are larger at age, live longer, and reach biological maturity at larger sizes compared to conspecifics from lower latitudes (Lam et al. in review, Head et al. in review?) (This fig. perhaps? A fig from Melissa too?). This known variability in life-history parameters and genetic structure has caused us to reexamine the Lingcod stock boundary used in previous assessments, located at the California - Oregon border (Hamel et al. 2006, Haltuch et al. 2017). 

A model based change-point analysis method outlined in Kapur et al. 2020 was used to identify a biologically relevant stock boundary using size-at-age data. Using size and age data from the WCGBTS (2004 - 2019) and an independent Lam study (Lam et al. in review), a generalized additive model was fit to a vector of observed lengths of Lingcod of a single age as the response variable, and predicted by a smoother for latitude. Each age-sex combination was analyzed separately. The first derivative was taken from the fitted spline to detect the latitude at which differences in size-at-age were most pronounced (i.e. the maximum absolute value) and statistically significant (i.e. where the confidence interval does not include 0). The resulting latitude was rounded to the nearest integer as there were no detectable differences when half-degrees were used. 77.8% of significant age-sex combinations detected a break between latitudes $38^\circ 00^\prime$ and $40^\circ 00^\prime$ N (Fig of derivative plots?). This range is in agreement with the genetic breakpoint identified for Lingcod by Longo et al. [-@longo2020strong]. 

A breakpoint at Cape Mendocino, California ($40^\circ 10^\prime$ N) was chosen for this assessment as it: 1.) falls in the vicinity of where the greatest difference in Lingcod size-at-age was detected, 2.) falls within the mixing zone of the two genetic clusters, and 3.) aligns with the federal management boundary for commercial quotas and a boundary between two CDFW management regions, which facilitates separation of historical catch and application of assessment results for future management.

*Ageing*    
Lingcod are aged using dorsal fin rays, which has been found to have the highest accuracy, readability, and minimal between-reader bias when compared to other ageing structures (e.g., [@chiltonAgeDeterm; @cass1983first; Claiborne et al. 2016); however recent studies suggest that surface reads from otoliths may be comparable in terms of accuracy and readability. For  this assessment, Lingcod samples from fishery-dependent and -independent sources were aged using the fin ray method. 

During the age reading process, the first and second annuli can be re-absorbed as the fish ages, obscuring early annulus rings and leading to error by under-ageing. However, error can be minimized using known mean annular radii measurements for the first, second, and third annuli, as established by Beamish and Chilton [-@beamish1977age] and later validated by McFarlane and King [-@mcfarlane2001validity].

For this assessment, between-reader ageing error was determined using the nwfscAgeingError package [@nwfscAgeingError2008],which is publicly available at https://github.com/nwfsc-assess/nwfscAgeingError. This package implements the Punt et al. [-@punt2008quantifying] model. It calculates the likelihood of model parameters given an observed dataset that includes age reads provided by multiple readers for a set of ageing structures. For each reader, two sets of parameters are estimated that define the standard deviation (SD) and bias of the reads provided by that reader. The set of parameters that best describes the SD and bias between age readers is determined with a stepwise model selection function and compared using AIC, the rationale of which is described more thoroughly in the documentation for the nwfscAgeingError package.  

## Ecosystem Considerations


## Historical and Current Fishery Information

Lingcod fisheries have a long history, with the earliest evidence of Lingcod fishing coming from the remains of 51 archaeological sites representing the period between 6200 BC and 1830 AD on the central California coast from San Mateo to San Luis Obispo [@gobalet1995prehistoric].  The commercial fishery off California dates back more than a century, and the fishery off of Washington and Oregon dates back nearly as far. Recorded commercial and recreational take of Lingcod began during the 1920s in southern California, and in the 1940s in Oregon and Washington. Lingcod are harvested commercially primarily by trawl and longline gear, and recreationally by hook-and-line and spear (see executive summary figures a and b).

The commercial fishery steadily grew with the rise of the groundfish trawl industry, reaching peak landings during the early 1980s. Landings decreased during the late 1980s due to population declines and the implementation of seasonal closures and size limits. In 1999 the Lingcod fishery was declared overfished coastwide. With the combination of a federal rebuilding plan implemented during 2003 and years of good recruitment, the population was deemed recovered in 2005, four years ahead of the projected recovery time.

In California, the recreational Lingcod fishery has had substantial landings that have surpassed that of the CA commercial fleet since 1998. At the peak of the Lingcod fishery, in 1974, the landings were nearly equally divided between the commercial and recreational fleets. From 1980 to 2008, 95% to 97% of Lingcod caught were taken by boat-based anglers (commercial passenger fishing vessel, CPFV, and private/rental boats). Private boat landings (including kayaks) were higher than those from CPFVs. A small fraction of landings are from spear fishers using SCUBA or free diving gear [@lynn2008status].

Catches of Lingcod in Oregon and Washington have shifted from the commercial trawl fleet, accounting for 90% of landings during its mid-1980s peak, to a fishery evenly split between commercial and recreational landings in recent years. Between 1980 and 1996, the majority of Lingcod were caught by the bottom trawl fishery (>75%), followed by troll and hook-and-line (between 10-20%), with a small fraction of additional landings from pots and traps, nets, and shrimp trawls [@jagielo1997assessment]. From 1999 to 2016, however, the recreational fishery has contributed about half of all Lingcod landings, on average, and has continued to grow.

## Summary of Management History and Performance

*Commercial Fishery*  
Prior to 1977, Lingcod stocks in the northeast Pacific were managed by the Canadian Government within its waters, and by the individual states in waters (out to three miles) off of the United States. With implementation of the Magnuson-Stevens Fishery Conservation and Management Act (MSA) in 1976, primary responsibility for management of the groundfish stocks off Washington, Oregon and California shifted from the states to the Pacific Fishery Management Council (PFMC). The U.S. west coast allowable biological catch (ABC) for Lingcod was set at 7,000 mt, but catch was consistently below this level. In 1994, a harvest guideline (HG) of 4,000 mt was set. In 1995, both the ABC and HG were dropped to 2,400 mt based on a quantitative assessment [@jagielo2000assessment].

Trip limits on commercial Lingcod catch were first instituted in 1995, when a 20,000 lbs./month limit was imposed, and a minimum size was imposed for recreational fisheries of 22 inches. Since 1998, managment has been through individual-year ABC and OY levels, and commercial trip limits became much more restrictive (starting at 1,000 mt bimonthly in 1998). 

<TOADS>

The PFMC implemented an initial Lingcod Rebuilding Plan in 2000 with size and seasonal limitations in the recreational fishery, and a change to limited entry and open access sectors in the commercial fishery. The coastwide ABC was further reduced by 27% (700 mt, down from 960 mt). In the commercial fishery sector, harvest guidelines in 2000 were reduced by over 80% from 1998 limits. In order to achieve these low harvest goals, all commercial fishing for Lingcod was closed for six months (January to April, and November to December). During the open period between April and November, all commercial vessels were limited to 400 pounds per month, and non-trawl vessels had a minimum size limit of 26 inches long south of Cape Mendocino ($40^\circ 10^\prime$ N), and 24 inches to the north.

Between 2000 and 2005, while the fishery was rebuilding, cumulative trip limits were very low, at 800 pounds bimonthly, with frequent closures. After 2006, ABC and trip limits began rising, with a bimonthly limit of 1,200 pounds. Concurrently, Marine Protected Areas (MPAs) in California, Rockfish Conservation Areas (RCAs) and the Cowcod Conservation Area (CCA) were established, in these areas take of all groundfish are prohibited within specified depths, habitats, and locations.

Between 2002 and 2011, observed trips were chosen by random stratified sampling. In 2011, the limited entry trawl sector became a catch share program with 100% observer coverage.  The Trawl Catch Share Program requires 100% at-sea observer coverage since all catch of Individual Fishing Quota (IFQ) species must be accounted for to allow fishers and managers to track and monitor their individual quotas.

*Recreational Fishery*  
Recreational regulations for Lingcod were established in 1994, included a bag limit of three fish in Washington and Oregon, five fish in California, and a minimum size limit of 22 inches in Washington and California. The 22 inch minimum size limit was adopted in Oregon in 1995 and increased to 24 inches in all three states in 1998.  In 1998, the bag limit in Washington and Clifornia dropped to two fish per day.  Oregon followed in 1999, and the two-fish bag limit largely remained coastwide until 2008. 

Regulations in all three states fluctuated frequently.  During the stock rebuilding period between 2000 and 2004, the California recreational bag limit dropped to 1 fish per day, and the size limit increased from 26 inches to 30 inches. In Oregon during this time, the bag limit fluctuated between and and two fish per day.  In recent years regulations have been more liberal that during the rebuilding period.  In 2015, the bag limit was increased to 3 fish per day in California, but a two-fish bag limit was retained in Oregon and Washington.  A size limit of 22 inches was adopted in all three states. More recently, the bag limit in California has decreased to 2 fish per day.

In Oregon, there have been multiple recreational groundfish in-season closures to reduce impacts to overfished rockfish. In 2020, Oregon retained two fish per day bag limits with a 22 inch minimum size limit. 

Summaries of regulatory histories for both federal and state management actions are available as supplementary materials to this stock assessment.  See table k in the executive summary for a recent history of OFLs, ACLs, landings, and catch (landings plus discards) for each area.

## Foreign Fisheries

Lingcod fisheries in the Gulf of Alaska are managed in state waters by the State of Alaska Board of Fisheries and in federal waters by the North Pacific Management Council. The sport fishery is restricted by daily bag and possession limits. Commercial fisheries are restricted by catch and bycatch quotas. Lingcod are a non-target species in the subsistence fishery.  No formal Lingcod stock assessment has been done in Alaskan waters.

Lingcod in Canada are managed under the Pacific Integrated Groundfish Fishery by the Department of Fisheries and Oceans for take by First Nations and the commercial and recreational sectors. Beginning in 1997, the Canadian commercial groundfish trawl fishery implemented an IVQ (Individual vessel quota) program that now incorporates all commercially caught trawl and hook and line groundfish. Stocks in distinct management areas are regularly assessed, with the most recent Lingcod assessment in outer British Columbia waters in 2011, and in the Strait of Georgia in 2014 [@DFO2016].

The 2011 outer British Columbia assessment implemented a Bayesian surplus production model to assess Lingcod stock status within four assessment areas. Overall the stock appears to have remained stable from 1927-1970, declined until 1980, increased until 1990 and has continued to decline since then. However, the stock was still estimated to be healthy with respect to reference points.

The 2016 assessment implemented a two-sex statistical catch-at-age model in a Bayesian framework. Results suggest that spawning biomass in 2014 is greater than spawning biomass at the start of the current management regime during 2006, and that the stock is likely in a precautionary management zone.

Southern California recreational fishers have reported fishing in Mexican waters and landing fish in U.S. ports. This is an issue that requires further investigation.

There are no known Mexican stock assessments for Lingcod.


