### Model changes from the last assessment

The following is a brief list of changes that were made to the
model configuration compared to the previous assessment
[@haltuch2019lingcod].

**Data**

- Change the boundary between north and south from \CAOR to \CapeM
- Add new data from 2017-2020
- Add new ages from earlier years in the \gls{s-wcgbt}
- Re-analyze all data inputs from the raw data with the exception of the 
trawl logbook index which was re-stratified to account for the change 
in boundary

**Fleet structure**

- Early and late periods of the \gls{s-tri} were combined into a 
continuous time-series
```{asis, opts.label = "south", echo = TRUE}
- The recreational CPFV DebWV index and associated 
length compositions were separated from the California recreational
fleet into into a new fleet to allow different
assumptions about selectivity
```
```{asis, opts.label = "north", echo = TRUE}
- A California recreational fishery for the catches
and length compositions between \CapeM and \CAOR was added
```

**Biology**

- Use new area-specific age-based maturity estimates
- Update weight-length relationship to include additional samples
- Separate $M$ priors for males and females based on a lower
maximum age (18 for females, 13 for males, compared to 21 for both sexes)
- Estimate female $M$ instead of fixing it at the mean of the prior
- Estimate all 5 growth parameters within each model rather than 
fixing the parameter controlling the length at age 14

**Recruitment**

- Fix $\sigma_R$ = 0.6 for both models (in the 2017 assessment, $\sigma_R$ had been iteratively 
tuned to 0.55 for the north model and 0.75 for the south)
- Estimate the stock-recruit steepness parameter with a prior instead of 
fixing it at 0.7
- Extend the end of the "main" period of recruitment deviations and the 
recruitment bias adjustment settings by three years to account for the 
additional survey data from 2017-2019 (no surveys were conducted in 2020
do the pandemic)

**Selectivity and retention**

- Estimate three double-normal selectivity parameters within each time block
for each fleet (whereas the previous model had fewer or more parameters
estimated depending on the fleet or time block)
- Fix the retention parameters for the early period of the commercial 
TW and FG fisheries to retain all selected fish prior to 1998
- Revise the blocking on numerous selectivity parameters
- Turn off male selectivity offsets to simplify the model

**Software and workflow**

- Use a newer version of Stock Synthesis, version 3.30.17.01
- Use previously unavailable or updated versions of numerous R packages 
related to processing input and output files for the assessment, 
including _nwfscDiag_, _sa4ss_, _r4ss_, and _PacFIN.Utilities_.
- Created a _lingcod_ R package in a
[publicly accessible repository](https::/github.com/iantaylor-NOAA/lingcod_2021)
on github to provide a transparent and reproducible system for processing
the data, modifying the model files, and writing these reports.
