#### Priors

The prior distributions for female and male natural mortality
(Figure \@ref(fig:compare-north-vs-south-pars)) were based on
the Hamel [-@hamel_method_2015] meta-analytic approach with an assumed maximum
age of 18 and 13 years old for females and males, respectively
(see Section \@ref(sec-biological-data) for details).

<!-- updatetext -->
The prior distribution for steepness (Figure \@ref(fig:compare-north-vs-south-pars))
was based on the prior distribution used
in the assessment of Pacific Hake, _Merluccius productus_ [@JTC2021],
which is based on the 20th, 50th, and 80th percentiles (0.67, 0.79, and 0.87, respectively)
from Myers et al. [@myers1999]. The prior has a beta distribution given the following
parameters: 9.76 and 2.80, which translates to a mean of 0.777 and a log-standard
deviation of 0.113. This prior has been used for Pacific Hake since 2007.
The terms of reference for groundfish managed by the \gls{pfmc} suggest that priors
on steepness for rockfish should have a mean of 0.72 and a standard deviation of 0.16
but do not specify anything related to `r spp`.
An analysis from [FishLife](github.com/James-Thorson/FishLife) suggested a prior
with a mean of 0.67 and a standard deviation of 0.22.

#### Estimated parameters

```{r parameters, include = FALSE, eval = TRUE, cache = TRUE}
# get parameter names from base model
estimated_pars <- model$parameters %>%
  dplyr::filter(!is.na(Active_Cnt)) %>%
  rownames()
  
estimated_pars <- estimated_pars[!grepl("ForeRecr", estimated_pars)]
nrecdevs <- sum(grepl("RecrDev", estimated_pars))
first_main <- min(model$recruit$Yr[model$recruit$era=="Main"])
last_main <- max(model$recruit$Yr[model$recruit$era=="Main"])
```

<!-- manual updates needed here -->
The base model has a total of `r length(estimated_pars)` estimated parameters
(Figure \@ref(fig:table-pars-base)) that can be grouped into the following
categories and are described in more detail in the following sections:

- 2 natural mortality parameters (female and male $M$)
- 10 growth parameters, where females and males each had
  - 3 von Bertalanffy parameters (length at age 0.5, length at age 14, and $k$)
  - 2 parameters controlling variability in growth, the CV in length at age 0.5
  and the CV in length at age 14 with a linear ramp in length-at-age
- `r 2 + sum(grepl("RecrDev", estimated_pars))` recruitment parameters
  - $log(R_0)$ controlling equilibrium recruitment
  - $h$ controlling the steepness of the stock-recruit relationship
  - `r nrow(model$recruit)` recruitment deviations parameters covering the range
  `r min(model$recruit$Yr)`-`r model$endyr`, with 
  `r first_main`-`r last_main`
  representing the "main" period modeled as a zero-centered deviation vector
- `r sum(sum(grepl("Q_extra", estimated_pars)))` extra standard deviation parameters
for indices
```{asis, exho = TRUE, eval = ifelse(params$area == "South", TRUE, FALSE)}
- 2 parameters representing the catchability in the two periods of the
index for the recreational California fleet (all other catchability values were 
derived analytical)
```
- `r sum(grepl("Size_DblN", estimated_pars))` selectivity parameters, of which
`r sum(grepl("Size_DblN.*BLK", estimated_pars))` represented changes over time
- `r sum(sum(grepl("Retain", estimated_pars)))` retention parameters, all of which
represented changes over time because the retention prior to 1998 was assumed to be
high for all selected fish.

#### Fixed parameters

Commercial fishery retention parameters for the period prior to 1998 were
fixed at values that led to almost 100\% retention.

```{asis, exho = TRUE, eval = ifelse(params$area == "North", TRUE, FALSE)}
[**TO DO: if north 2021.n.020.001 is the base model,
describe the reasons for fixing 3 selectivity parameters that were hitting the bounds]
```

The following additional parameters were fixed based on standard practices for west coast assessments.
```{asis, exho = TRUE, eval = !any(grepl("sigma", estimated_pars))}
The standard deviation of recruitment deviations was fixed at
`r sprintf("%.2f", model$parameters %>% dplyr::filter(grepl("sigma",Label)) %>% dplyr::pull(Value))`.
```
```{asis, exho = TRUE, eval = !any(grepl("Mat", estimated_pars))}
The maturity parameters were fixed at values based on the analysis described in Section
\@ref(sec-biological-data-maturation-and-fecundity).
```
```{asis, exho = TRUE, eval = !any(grepl("Wtlen", estimated_pars))}
The weight-length parameters were fixed at values estimated externally using data
with paired observations of length and weight from the \gls{s-wcgbt}
\@ref(sec-biological-data-Length-Weight-relationship).
```
