```{r comparison-load-model-summaries, eval = TRUE, echo = FALSE}
# read ss_summary.sso files for each area
vals.n <- file.path("..", "models",
                    info_basemodels[["North"]],
                    "ss_summary.sso") %>%
  r4ss::SS_read_summary()
vals.s <- file.path("..", "models",
                    info_basemodels[["South"]],
                    "ss_summary.sso") %>%
  r4ss::SS_read_summary()

# get M estimates for each area/sex
M.f.n <- vals.n[["parameters"]]["NatM_uniform_Fem_GP_1", "Value"] %>% as.numeric %>% round(3)
M.m.n <- vals.n[["parameters"]]["NatM_uniform_Mal_GP_1", "Value"] %>% as.numeric %>% round(3)
M.f.s <- vals.s[["parameters"]]["NatM_uniform_Fem_GP_1", "Value"] %>% as.numeric %>% round(3)
M.m.s <- vals.s[["parameters"]]["NatM_uniform_Mal_GP_1", "Value"] %>% as.numeric %>% round(3)

# unfished spawning and summary biomass 
smry.n <- vals.n[["derived_quants"]]["SmryBio_unfished","Value"] %>%
  as.numeric %>%
  round() %>% 
  format(., big.mark = ',')
smry.s <- vals.s[["derived_quants"]]["SmryBio_unfished","Value"] %>%
  as.numeric %>%
  round() %>% 
  format(., big.mark = ',')
SSB.n <- vals.n[["derived_quants"]]["SSB_unfished","Value"] %>%
  as.numeric %>%
  round() %>%
  format(., big.mark = ',')
SSB.s <- vals.s[["derived_quants"]]["SSB_unfished","Value"] %>%
  as.numeric %>%
  round() %>%
  format(., big.mark = ',')

# # catchability when calculated as a float is not 
# # available in ss_summary.sso
# Q.n <- mod.n$cpue$Eff_Q[mod.n$cpue$Fleet == 7][1]

```

The north and south models represent genetically distinct
sub-populations of `r spp` and may differ in numerous ways.
However, there are enough similarities
in management, fisheries, and biology that some similarity 
across these stocks and the models used to represent them
is to be expected. A fundamental challenge
in fisheries stock assessment is understanding spatial
variability among stocks and finding appropriate ways to
share information across stocks [@punt101093/icesjms/fsr039].
The following section is intended to provide information regarding
the evaluation of the plausibility of the estimates for the two areas.

Estimates of growth in the two areas match prior expectations for males
with faster growth in the north relative to
the south (Figure \@ref(fig:compare-north-vs-south-growth)), but females
are estimated to growth to a slightly larger size in the south.
The estimated variability in growth is smaller in the north compared to the south,
which may reflect differences in biology or a greater spatial
heterogeneity in growth in the south. Estimated growth in both areas use
a reference age of 14 for mean length at age,
<!-- manual update: Linf not available in SS_summary.sso
`r model$Growth_Parameters$Linf %>% round(1) %>% 
paste(collapse = " and ")` 

mod.2021.n.023.001$Growth_Parameters$Linf %>% round(1)
[1] 118.7  77.5
mod.2021.s.018.001$Growth_Parameters$Linf %>% round(1)
[1] 122.6  65.2
-->
but the corresponding $L_\infty$ values are 118.7 
and 77.5 
for females and males respectively in the north
and 122.6 and 65.2
in the south. The estimated length at age 14 in the north is more precise 
than in the south (Figure \@ref(fig:compare-north-vs-south-pars)), 
reflecting the larger volume of conditional age-at-length data include in 
the north model. Thus, the estimate of larger $L_\infty$ in the south 
is unlikely to be statistically significant.

Estimates of key productivity parameters (i.e., $M$ and $h$)
differ significantly among the 
two areas, indicating that the southern stock is less productive than the northern stock
(Figure \@ref(fig:compare-north-vs-south-pars)).
Additionally, the north model estimates almost
equal $M$ for females and males (`r M.f.n` and `r M.m.n` respectively), 
whereas the south model has a lower estimate of female $M$ than
male $M$ (`r M.f.s` and `r M.m.s`). The $M$ estimates 
are uncertain in both models, although more so in the south than the north.

Estimates of unfished spawning biomass in the two areas are higher in the south
than the north
(`r SSB.n` mt and `r SSB.s` mt for north and south), but this comparison
is misleading due to the differences in $M$ between areas resulting in
a smaller fraction of recruits reaching spawning ages in the north than
the south. The estimates of unfished age-3+ biomass are similar: `r smry.n` mt 
and `r smry.s` mt for the north and south 
(Figure \@ref(fig:compare-north-vs-south-quants)).
The differences in estimated \glspl{msy} are larger than those for biomass
because the lower estimates of $M$ and $h$ in the south equate to 
lower productivity relative to stock size.

There are no precise estimates for the amount of `r spp` habitat in either area,
but a rough approximation can be found by calculating the spatial extent of
the \gls{s-wcgbt} survey area between the 55 m inner limit and 300 m, a depth 
which represents a decline in frequency of `r spp` in that survey.
By this measure, the ratio of north to south areas is about 2.3:1.
<!-- value taken from https://github.com/iantaylor-NOAA/Lingcod_2021/issues/79 -->
Thus, the biomass estimates are more closer to each other than would be expected had the
densities been equal in the two areas.
However, one must account for catchability and because the \gls{s-wcgbt} does not provide an absolute estimate of abundance
with a non-trivial amount of habitat and biomass inside the 55 m isobath.
The estimated
catchability of the \gls{s-wcgbt} is similar among areas,
<!-- manual updates: values not dynamic
mod.2021.n.023.001$cpue$Calc_Q[mod.2021.n.023.001$cpue$Fleet == 7][1]
[1] 0.811244
mod.2021.s.018.001$cpue$Calc_Q[mod.2021.s.018.001$cpue$Fleet == 7][1]
[1] 0.95467
-->
0.81 in the north and 0.95 in the south.


<!-- manual updates: values not dynamic
plot_twopanel_comparison(list(mod.2021.n.023.103, mod.2021.s.018.103))
mod.2021.n.023.001$cpue$Calc_Q[mod.2021.n.023.001$cpue$Fleet == 7][1]
[1] 2.05056
mod.2021.s.018.001$cpue$Calc_Q[mod.2021.s.018.001$cpue$Fleet == 7][1]
[1] 0.315127
mod.2021.s.018.103$derived_quants["Bratio_2021","Value"]
[1] 0.905011
-->
The differences in scale among the two areas are less plausible when matching 
values are used for the productivity parameters 
(fixing female $M$ = 0.3 and $h$ = 0.7). In those sensititivity analyses, the 
estimated spawning biomass in the south model is greater than that of the north 
for almost all years from the 1940s onward and never falls below $B_{40\%}$.
The catchability of the \gls{s-wcgbt} in those scenarios is likewise
implausibly different: 2.05 in the north and 0.32 in the south
Thus, the different parameter estimates for the north and south play an 
important role in providing values for quantities of interest that are balanced
among the two model, and likely provide better advice for managing the `r spp`
lingcod stocks throughout the U.S. west coast.

