#### Parameter estimates {#sec-model-estimates}

Estimates of key parameters include 
female $M$ = 
`r round(model$parameters["NatM_uniform_Fem_GP_1", "Value"], 3)`, 
male $M$ = 
`r round(model$parameters["NatM_uniform_Mal_GP_1", "Value"], 3)`, and
stock-recruit steepness $h$ = 
`r round(model$parameters["SR_BH_steep", "Value"], 3)` 
(Table \ref{tab:table-pars-base}). 
Females were estimated as growing larger than males with female length at age 14
(the second reference age) equal to 
`r round(model$parameters["L_at_Amax_Fem_GP_1", "Value"], 1)` cm compared to
`r round(model$parameters["L_at_Amax_Mal_GP_1", "Value"], 1)` cm for males.
The $L_\infty$ associated with the estimated growth parameters was 
`r round(model$Growth_Parameters$Linf[1], 1)` cm for females and
`r round(model$Growth_Parameters$Linf[2], 1)` cm for males.

<!-- selectivity text below needs manual updates for any model change-->
```{asis, echo = TRUE, eval = ifelse(params$area == "North", TRUE, FALSE)}
Selectivity was estimated as asymptotic for the commercial fixed-gear fleet and the 
earliest period of the commercial trawl fleet, while from 1993 onward the commercial
trawl fishery was estimated as asymptotic
(Figure \ref{fig:selectivity_comm}).
```

```{asis, echo = TRUE, eval = ifelse(params$area == "South", TRUE, FALSE)}
Selectivity was estimated as dome-shaped for all fleets. The estimated changes
over time for the commercial trawl sector was a shift in selectivity toward larger
fish over time. with the peak selectivity from 2011 onward estimated at
`r round(model$parameters["Size_DblN_peak_1_Comm_Trawl(1)_BLK1repl_2011", "Value"], 1)` cm.
Peak selectivity for the time-invariant commercial fixed-gear fishery was estimated at
`r round(model$parameters["Size_DblN_peak_2_Comm_Fix(2)", "Value"], 1)` cm 
(Figure \ref{fig:selectivity_comm}).
```

Commercial trawl retention was estimated as shifting to the right during the 
period with strict trip limits from 1998 to 2009, then shifting back to the 
left as catch shares were implemented, with the length at 50\% retention from 2011 
onward estimated at
`r round(model$parameters["Retain_L_infl_1_Comm_Trawl(1)_BLK2repl_2011", "Value"], 1)` cm.

```{asis, echo = TRUE, eval = ifelse(params$area == "North", TRUE, FALSE)}
The recreational fishery selectivity in Washington was estimated as asymptotic 
in the early and late periods but dome-shaped during the two blocks covering the years
1998-2010. Oregon and California recreational selectivity was estimated as asymptotic
for most time blocks, but dome-shaped in the most recent block in each case
(Figure \ref{fig:selectivity-noncomm}).

Selectivity for the two surveys and the Lam research sampling were all estimated as 
dome-shaped although the \gls{s-tri} is almost asymptotic. Peak selectivity is estimated at 
`r round(model$parameters["Size_DblN_peak_6_Surv_TRI(6)", "Value"], 1)` cm for the
\gls{s-tri} and 
`r round(model$parameters["Size_DblN_peak_7_Surv_WCGBTS(7)", "Value"], 1)` cm for the
\gls{s-wcgbt}. The survey selectivity is notably different
from the south model, where those two surveys have peak selectivity below 30 cm
(Figure \ref{fig:selectivity-noncomm}). 
Strong differences in the presence of small 
fish in the survey samples from the north and south areas indicate that the 
differences in estimated selectivity curves are necessary to fit the data in each case.
```
```{asis, echo = TRUE, eval = ifelse(params$area == "South", TRUE, FALSE)}
The changes in the recreational California selectivity were subtle and presumably 
driven primarily by changes in minimum size limits. The \gls{s-tri} and \gls{s-wcgbt}
selected more small fish than other fleets, with peak selectivity at 
`r round(model$parameters["Size_DblN_peak_6_Surv_TRI(6)", "Value"], 1)` cm and 
`r round(model$parameters["Size_DblN_peak_7_Surv_WCGBTS(7)", "Value"], 1)` cm,
respectively, while selectivity for the \gls{s-hkl} peaked at the largest size, 
`r round(model$parameters["Size_DblN_peak_8_Surv_HookLine(8)", "Value"], 1)` cm
(Figure \ref{fig:selectivity-noncomm}). The survey selectivity is notably different
from the north model, where the peak is above 80 cm for all surveys.
Strong differences in the presence of small 
fish in the survey samples from the north and south areas indicate that the 
differences in estimated selectivity curves are necessary to fit the data in each case.
```

#### Fits to the data {#sec-model-fits}

```{asis, echo = TRUE, eval = ifelse(params$area == "North", TRUE, FALSE)}
The fit to the seven indices of abundance are all reasonably good, with 
the timing and magnitude of changes in expected abundance following the 
observed patterns (Figure \ref{fig:index-fits-all-fleets}). 
The five contemporary indices all increased over the 2010s with a peak 
around 2005, which the model expectation fits well driven by a large 2008 cohort. 
The areas with the biggest lack of fit are the first two years of the 
trawl logbook CPUE index, which are much higher than the rest of the time series,
and are also poorly fit in the south model, 
the 2004 observations of the \gls{s-tri}, and the 2020 observation of 
the Washington recreational CPUE index. All of these observations are 
inconsistent with the adjacent observations in the same index suggesting 
that they may be outlier rather than a signal about the true dynamics of 
the underlying population.

The fit to the length data, when aggregated over time 
(Figure \ref{fig:comp-lenfit--aggregated-across-time}), shows 
some imbalances in the sex ratios but the modes are generally falling in the right
places. The commercial trawl discards show modes associated with 
the length at ages 1 and 2 the first of which is better fit than the second. 
This could be due to the fishery taking places over a protracted season while the model
expectation is based on a mid-year snapshot. Looking at the 
fits for individual years
(Figures \@ref(fig:comp-lenfit--page1-multi-fleet-comparison) and \@ref(fig:comp-lenfit--page2-multi-fleet-comparison))
shows high variability for the 
commercial trawl length comps and a large blotches in the Pearson residuals.
In general, the recreational and survey length compositions are reasonably well fit.

Ages in the north model are all conditioned on length, but also included as
marginal "ghost age comps" which are excluded
from the likelihood for purposes of 
visualizing the implied fit. These data do not show strong cohorts very clearly,
although some modes progress through the population, such as the 2008 cohort 
as observed by the \gls{s-wcgbt} in the years 2008-2011 (the observed mode in 2012 
is off by 1 year). 

<!-- manual updates needed here if models change -->
<!-- values in paragraph below (and comparable for south model) are from 
dat.n <- get_inputs_ling('n', 23)$dat
sum(dat.n$agecomp$Nsamp[dat.n$agecomp$Lbin_lo > 0])
sum(dat.n$agecomp$Nsamp[dat.n$agecomp$FltSvy == 7 & dat.n$agecomp$Lbin_lo > 0])
dat.s <- get_inputs_ling('s', 18)$dat
sum(dat.s$agecomp$Nsamp[dat.s$agecomp$Lbin_lo > 0])
-->
The conditional age-at-length data (CAAL) in the north model are numerous
(`r ref_range(figurecsv, grep = "cond.+resid", fleets = get_fleet(col = "num"), encapsulate = FALSE)`). 
They represent over 72,000 individual fish
from a total of 161 fleet/year combinations. In general, most years and most fleets 
show no strong patterns in the Pearson residuals, but there are a few exceptions
(`r ref_range(figurecsv, grep = "cond.+resid", fleets = get_fleet(col = "num"), encapsulate = FALSE)`).
For instance, the commercial trawl fit in 1980 has many fish older than expected
within all of the smaller length bins, while in 1981 the ages observations
all fall in the middle of the expected range.
Both the mean age in each length bin and the variability in age at length
have a good match for most years and most fleets.

The expected commercial trawl discard fractions 
(`r ref_range(figurecsv, grep = "dis.+fit", column = "file", fleets = "comm", encapsulate = FALSE)`)
are higher than observed for the period 2002-2009, where
the large uncertainty in estimated discards allows the model to misfit these 
to better fit the length comps, with the parameter for length at 50\% retention
pushed to the upper bound as discussed in Section \ref{sec-model-selection}. 
However, discards prior to 1998 are assumed to be low
and the fits from 2010 onward are good, so the impact of the lack of fit on 
the estimated mortality is limited to a 12-year period. The commercial fixed-gear
discards show less variability over time, are more uncertain, and the fits
are well within the uncertainty intervals for all but 2002.

The fit to the mean body weight of discards are good for most years
although the observed discards in the first two years (2002 and 2003) were lighter 
than the expectation
(`r ref_range(figurecsv, grep = "bodywt.+fit", column = "file", fleets = "comm", encapsulate = FALSE)`).
There are no discard length compositions from those years
so it's difficult to judge the reasons for the lack of fit.
```
```{asis, echo = TRUE, eval = ifelse(params$area == "South", TRUE, FALSE)}
The fit to the six indices of abundance available for the south model
are reasonably good although many of the indices are noisier than for the north
model reflecting the smaller sample sizes associated with the smaller area
(Figure \ref{fig:index-fits-all-fleets}).
The first two years of trawl logbook CPUE are poorly fit but they 
are much higher than the rest of the time series,
and are also poorly fit in the north model.
observed patterns (Figure \ref{fig:index-fits-all-fleets}). 
The recreational California CPUE and the \gls{s-wcgbt} both show a the strong
increase starting in 2010. The rec CA peaks in 2016 while the \gls{s-wcgbt}
is stable across 2014-2016. In the 2017 STAR, the conflict between these
indices led to the removal of the CPUE index, but the addition of a low 2019
observation in the \gls{s-wcgbt} makes these indices appear more consistent than 
before. The lack of 2020 survey due to the COVID-19 pandemic makes
it harder to judge whether the 2019 \gls{s-wcgbt} observation is an outlier
or representing a steep decline in selected biomass.

The fit to the length data in the south model is generally good, in aggregate
(Figure \ref{fig:comp-lenfit--aggregated-across-time}). The limited number of 
ages in the south model means that there is less potential conflict among data 
sources than in the north. Many sources show clear size modes, including 
the commercial trawl discards, the \gls{s-tri}, and the \gls{s-wcgbt}.
In general these are well fit. The \gls{s-wcgbt} is estimated as selecting 
smaller fish in the south than in the north and shows modes indicating strong
cohorts for all years 2007-2010, 
whereas the north model had a single large
estimated 2008 cohort. Pearson residuals for the commercial trawl show some noise
and lack of fit, but there are few clear trends in the residuals. 
Some of the biggest
residuals come from the recreational California length compositions but this
source represents multiple sampling programs with regional variability in
sampling location, so some lack of fit is to be expected.

Early explorations of the south model showed bad patterns in the fit to the 
age data from the commercial trawl fishery, leading to the removal of all
ages other than those from \gls{s-wcgbt} in the final model. Nevertheless,
these ages are included as marginal "ghost age comps"
which are excluded from the likelihood for purposes of visualizing the implied fit. 
The implied fit to the ages from the commercial trawl and fixed-gear fleets
show expected modes at younger ages than observed as discussed in 
Section \ref{sec-model-selection}. The implied fits to the \gls{s-tri} is good
even though these data are not included in the model likelihood.

The ages included in the south model are all from the \gls{s-wcgbt} survey
and are represented as \gls{caal} data
(shown for \gls{s-wcgbt} in
`r ref_range(figurecsv, grep = "cond.+resid", fleets = get_fleet("WCGBTS", col = "num"), encapsulate = FALSE)`).
These represent about 3,400 fish (compared to over
72,000 in the north model, of which about 5,000 were from the \gls{s-wcgbt}).
The fits to these data are all reasonably good, although the expected proportion
of males older than 10 years is greater than observed in many years.
The observed data would be more consistent with a higher mortality rate for males
but the estimated values are similar among the rates, presumably driven by 
information in the larger volume of length data.
The mean age within these data rises from about 2.5 in 2003 to almost
5 in 2007 followed by a steep decline as the addition of new recruits brings
down the mean observed age.

The expected commercial trawl discard fractions 
are lower than observed for the first four years but otherwise are relatively well fit
(`r ref_range(figurecsv, grep = "dis.+fit", column = "file", fleets = "comm", encapsulate = FALSE)`).
The most estimates match the observed decline in discard rate over the most recent 
7 years, which is likely driven by the shift toward larger individuals as the above
cohorts born in the 2007-2010 period grew older. The commercial fixed-gear
discards show little variability over time and the fits
are well within the uncertainty intervals.

The fit to the mean body weight ("Mnwt") of discards are within the confidence
intervals for most years although there's relatively little signal in those data
(`r ref_range(figurecsv, grep = "bodywt.+fit", column = "file", fleets = "comm", encapsulate = FALSE)`).
```

#### Population trajectory {#sec-model-trajectory}

The spawning stock biomass is estimated as having declined from an unfished 
equilibrium of `r format(SSB_Virgin, big.mark = ",")` mt to a 2021 value of 
`r format(SSB_2021, big.mark = ",")` mt, which represents a
fraction unfished of `r Bratio_2021`. The lowest fraction unfished was 
`r Bratio_min` in `r Bratio_min_yr` 
(Figures \ref{fig:ts7-Spawning-biomass-(mt)-with-95-asymptotic-intervals-intervals} and
\ref{fig:ts9-Relative-spawning-biomass-intervals}). 
The 2021 total biomass (all ages from both sexes) was 
`r format(TotBio_2021, big.mark = ",")` mt (Figure \ref{fig:ts1-Total-biomass-(mt)}).

The last large recruitment event for this stock occurred in 2013 and
a smaller event may have also occurred within the last half-decade,
though its magnitude is more uncertain
(Figures \ref{fig:ts11-Age-0-recruits-(1000s)-with-95-asymptotic-intervals}--\ref{fig:recdevs2-withbars}).
Most large recruitment events appear to preceded or followed by 
a smaller number of similarly large recruitment events compared to
the number of poor recruitment events that occur before another
recruitment event that is estimated to be above average.
There is little information regarding recruitment prior to
`r model$recruitpars %>% dplyr::filter(type == "Early_RecrDev") %>% dplyr::pull(Yr) %>% max`, and thus,
these early recruitment events fall on the stock-recruitment curve
(Figure \ref{fig:SR-curve}).
