#### \acrlong{s-wcgbt} {#s-wcgbt}

The \Gls{s-wcgbt}, which began in 2003,
is the longest time series of fishery-independent data
included in this assessment and the most recent.
This survey samples the shelf and slope off the U.S. West Coast covering depths
from 30 - 700 fathoms (55 - 1,280 meters; Figure \@ref(fig:s-wcgbt-VAST_inputgrid))
on an annual basis (excluding 2020 due to COVID-19).
The survey is based on a random-grid design [@bradburn_2003_2011] that
generally uses four industry-chartered vessels per year
assigned to a roughly equal number of randomly selected grid cells and
 divided into two 'passes' of the coast.
Two vessels fish from north to south during each pass between late May to early October.
This design therefore incorporates vessel-to-vessel differences in catchability
and variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

Three sources of information are produced from the \Gls{s-wcgbt}, an index of relative
abundance, length-composition distributions, and age-composition distributions. Length-weight 
parameters were also estimated from data collected from the \Gls{s-wcgbt}
(see Section \@ref(sec-biological-data) for details).

The data from the \gls{s-wcgbt} was analyzed using a
spatio-temporal delta-model [@thorson_geostatistical_2015],
implemented as an R package, VAST [@thorson_comparing_2017],
which is publicly available [online](https://github.com/James-Thorson/VAST).
Spatial and spatio-temporal variation is specifically included in both
encounter probability and positive catch rates,
a logit-link for encounter probability and
a log-link for positive catch rates.
Vessel-year effects were included for each unique combination of
vessel and year in the data to account for the random selection of
commercial vessels used during sampling
[@helser_generalized_2004; @thorson_accounting_2014].
Spatial variation was approximated using 500 knots (Figure \@ref(fig:s-wcgbt-VAST_mesh)),
and the model used the bias-correction algorithm
[@thorson_implementing_2016] in Template Model Builder [@kristensen_tmb:_2016].

The estimated index of abundance (Figure \@ref(fig:index-fits-all-fleets))
was assumed to follow a gamma distribution
(Figure \@ref(fig:s-wcgbt-VAST-QQ))
but both the lognormal and the gamma fit equally well.
The quantile-quantile plot did not a significant departure from the
theoretical quantiles (Figure \@ref(fig:)) and
the gradient was sufficiently low to the model had converged.
Furthermore, there was no clear pattern in residuals (Figure \ref{fig:wcgbt-resid}). Separate models were fit for each area rather than
using the stratification functionality to partition the results from a single
model to multiple areas. This was done to ensure that the correlation structure
from one area did not influence the estimates from another area.

#### \acrlong{s-tri}

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey continued until 2004 [@weinberg_2001_2002].
Its basic design was a series of equally-spaced east-to-west transects across the continental shelf from which searches for tows in a specific depth range were initiated.
The survey design changed slightly over time.
In general, all of the surveys were conducted in the mid summer through early fall.
The 1977 survey was conducted from early July through late September.
The surveys from 1980 through 1989 were conducted from mid-July to late September.
The 1992 survey was conducted from mid July through early October.
The 1995 survey was conducted from early June through late August.
The 1998 survey was conducted from early June through early August.
Finally, the 2001 and 2004 surveys were conducted from May to July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls shallower than 91 m.
Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted from this analysis.
The surveys in 1980, 1983, and 1986 covered the US West Coast south to 36.8\textdegree N latitude and a depth range of 55-366 m.
The surveys in 1989 and 1992 covered the same depth range but extended the southern range to 34.5\textdegree N (near Point Conception).
From 1995 through 2004, the surveys covered the depth range 55-500 m and surveyed south to 34.5\textdegree N.
In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} conducted the survey following similar protocols to earlier years.

The triennial data have historically been split into early (1980-1992) 
and late (1995-2004) survey time series and treated independently; however
for this assessment, we combined across time series into a single fleet.

\Glsentrylong{vast} was used in the same manner as was done for
(Figure \@ref(s-wcgbt)). The lognormal distribution with random strata-year and vessel effects fit the data well (Figures \@ref(fig:) and \@ref(fig:)) and
had a low gradient.

The index was generally cup shaped but with a large spike up in 2004,
the terminal year (Figure \@ref(fig:index_fits_all_fleets)).
The 2004 data point increased at a rate beyond what may be anticipated given the life history of `r spp`.
A similar spike in abundance in 2004 has been observed for other species sampled (e.g., petrale sole, dover) observed in the \gls{s-tri} which
may be indicative of a change in the application of the survey
rather than an increase in biomass.

```{asis, opts.label = 'south', echo = TRUE}
#### NWFSC Hook and Line Survey

Since 2004, the \gls{nwfsc} has conducted an annual hook and line survey
targeting shelf rockfish in the genus Sebastes at fixed stations in the
Southern California Bight. Key species of rockfish targeted by the survey are
bocaccio (*S. paucispinis*), cowcod (*S. levis*), greenspotted
(*S. chlorostictus*), and vermilion (*S. miniatus* and *S. crocotulus*)
rockfishes,
<!--check that these species are not already listed -->
although a wide range of groundfish species have been observed by this survey, including lingcod, and therefore provide potentially useful data for this assessment. 
Starting in 2014 the NWFSC Hook and Line Survey added sampling sites located
within the \gls{cca} and currently consists of a total of 201 sites. 

During each site visit, three deckhands simultaneously deploy
5-hook sampling rigs (this is referred to as a single drop)
for a maximum of 5 minutes per line, but individual lines may be retrieved
sooner at the angler’s discretion (e.g., to avoid losing fish).
Five drops are attempted at each site for a maximum possible catch of
75 fish per site per year (3 anglers x 5 hooks x 5 drops).
Further details regarding the sample frame, site selection,
and survey methodology are described by Harms et al. [-@harms2008].


`r Spp` is a commonly encountered species in the NWFSC hook-and-line survey (Figure \@ref(fig:spp-sites)). Sample sizes by depth and year can be found in Tables 
\@ref(tab:tab-depth-nwfschl) and \@ref(tab:tab-year-nwfschl).
Note that depth was used as a continuous variable in the model, and depth bins were created for data exploration only. 

A number of distributions were explored to fit an appropriate error distribution to the data.
The final model included terms for Year, Site, Drop number within a site,
second order depth, and a random effect for each observation.

Models were fit using the “rstanarm” R package (version 2.21.1). Posterior predictive 
checks of the Bayesian model fit for the binomial model and the positive model 
were all reasonable (Figures \@ref(fig:fig-posterior-mean-nwfschl)  and 
 \@ref(fig:fig-posterior-sd-nwfschl)). The model generated data sets with the 
 proportion of zeros similar to the observed data (91\%; Figure \@ref(fig:fig-propzero-nwfschl)).
The depth effect is masked by the site effect in the marginal effects (Figures \@ref(fig:marginal-nwfschl).
A model without Site confirms that that depth follows the expected pattern observed in the data.
The final index represents a similar trend to the arithmetic mean of the annual CPUE (Figure \@ref(fig:index_fits_all_fleets)).
```