#### \Glsentrylong{s-wcgbt} lengths

The length frequency of survey catches in each year was summarized using length bins in 
2 cm increments from 10 to 130 cm (Figure \@ref(fig:wcgbts-lenComp)).
The first bin includes all observations less than 10 cm, 
and the last bin includes all fish larger than 130 cm. The observed length compositions were 
expanded to account for subsampling of tows, and the expansion was stratified by depth. Depth 
strata of 55 - 183 m and 183 - 400m were selected,
based on the sampling design of the survey (@keller2017).
Depth strata were capped at 400 m because catches of `r spp` in 
the \Gls{s-wcgbt} occur infrequency beyond 400m (Figure \ref{fig:wcgbts-presAbs}). Samples were
often sexed, so only male and female length frequencies were used. The few unsexed individuals 
were assigned as male or female according to the sex ratio of the respective length bin. An 
assumed sex ratio of 0.5 was applied for unsexed fish in length bin less than 40 cm, as sex 
of smaller sized `r spp` is harder to differentiate. A bin of 40 cm was chosen as this is the
length bin at which the length-weight relationship starts to diverge for males and females, 
and therefore equal assignment is not influenced by sex-specific size differences.
Figure  shows the length-frequency distributions for the \Gls{s-wcgbt}.

The input sample sizes (Table \@ref(tab:tab:sample-size-length))
for length and marginal age-composition data for all 
fishery-independent surveys were calculated according to 
Stewart and Hamel [-@stewart_bootstrapping_2014], which determined that the 
approximate realized sample size for species in the "others" category 
(which included `r spp`) was $2.38*N_{\text{tow}}$.

#### \acrlong{s-tri} lengths

Length data preparation followed the same methods as applied to the WCBTS data,
but depth strata of 55 - 183 m and 183 - 350m were used for expanding the
length comps for subsampling of tows. A depth split of 183 m was used because
sampling appeared less intense after this depth and raw catch per unit effort 
more variable (Figure \ref{fig:tri-depthSplit}). A maximum
depth of 350 m was used because `r spp` were infrequently caught at depths 
greater than 350 m (Figure \ref{fig:tri-depthSplit}). 
Figure \ref{fig:tri-lenComp} shows the length frequency distributions for the \gls{s-tri}. 
Table \ref{tab:sample-size-length} shows the sample sizes.

#### \Glsentrylong{s-hkl} lengths

The length frequency of survey catches in each year was summarized using length bins in 
2 cm increments from 10 to 130 cm (Figures \ref{fig:hkl-lenComp-sexed} and \ref{fig:hkl-lenComp-unsexed}).
The first bin includes all observations less than 10 cm, 
and the last bin includes all fish larger than 130 cm. Length compositions from this 
survey were used as numbers of fish, all fish were measured, and were not expanded.
As such, composition data are available for male, female, and unsexed `r spp`. 
Table \ref{tab:sample-size-length} show the sample sizes.

#### Lam research lengths

In collaboration with the NWFSC and Moss Landing Marine Labs, `r spp` in nearshore 
and offshore rocky reef habitats were collected between January 2016 and January 
2017 via hook and line on chartered CPFVs (@lam2019geographic). Sixteen latitudinal distinct sampling 
sites, or ports, were chosen from northern Washington to southern California. 85 
to 120 individuals were caught per port (N = 1,784, 922 Males, 862 Females) using 
methods identical to those used by the onboard recreational lingcod fishery 
except that shorts were retained (individuals smaller than the legal-size limit 
of 22 inches) and areas closed to recreational harvest were occasionally utilized 
(CDFW Permit #SC-6477, ODFW Permit #20237, WDFW Permit ID Samhouri 16-138). 
This was to ensure an even distribution of size and age classes from each port 
for purposes of comparing `r spp` von Bertalanffy growth curves by spatially 
explicit regions. Of the total fish samples, 32 were sampled on CCFRP trips and so to avoid double 
counting were excluded. Four addition samples had no year associated with them, and
were excluded. Length compositions from this survey were used as numbers of fish, 
and were not expanded. Lengths were measured in total length, and were converted to
fork length following conversions from Laidig et al. [-@laidig_lingcod_conversions_1997]. Total
and fork lengths for `r spp` were generally very similar given the tail shape 
of `r spp`. 
Figure \ref{fig:lam-lenComp} shows the length frequency distributions. 
Table \ref{tab:sample-size-length} shows sample sizes.

#### \Glsentrylong{s-wcgbt} ages

Age-frequency data from the \Gls{s-wcgbt} (Figure \ref{fig:wcgbts-ageComp}) were 
included in the model as conditional age-at-length (CAAL) distributions by sex 
(male and female) and year, and therefore were not expanded. The numbers of fish 
are used without any adjustment. The age distribution of survey catches in each year 
was summarized using age bins from 0 to 20 years, in increments of one year. The last bin 
includes all fished aged to be greater than 20 years. 

Individual length- and age-observations can be thought 
of as entries in an age-length key (matrix), with age across the columns and length 
down the rows. The CAAL approach consists of tabulating the sums within rows as the 
standard length-frequency distribution and, instead of also tabulating the sums to 
the age margin , the distribution of ages in each row of the age-length key is 
treated as a separate observation, conditioned on the row (length) from which it came. 

The CAAL approach has several benefits for analysis above the standard use of marginal age 
compositions. First, age structures are generally collected as a subset of the fish 
that have been measured. If the ages are to be used to create an external age-length 
key to transform the lengths to ages, then the uncertainty due to sampling and missing 
data in the key are not included in the resulting age-compositions used in the stock 
assessment. If the marginal age compositions are used with the length compositions 
in the assessment, the information content on sex-ratio and year class strength is 
largely double-counted as the same fish are contributing to likelihood components 
that are assumed to be independent. Using conditional age distributions for each 
length bin allows only the additional information provided by the limited age data 
(relative to the generally far more numerous length observations) to be captured, 
without creating a ‘double-counting’ of the data in the total likelihood. The second 
major benefit of using conditional age-composition observations is that in addition 
to being able to estimate the basic growth parameters ($LminAge$, $LmaxAge$, $K$) inside 
the assessment model, the distribution of lengths at a given age, governed by two 
parameters for the standard deviation of length at a young age and the standard 
deviation at an older age, is also quite reliably estimated. This information could 
only be derived from marginal age-composition observations where very strong and 
well-separated cohorts existed and where they were quite accurately aged and measured; 
rare conditions at best. By fully estimating the growth specifications within the 
stock assessment model, this major source of uncertainty is included in the assessment 
results, and bias in the observation of length-at-age is avoided. 

The CAAL approach was only applied for male and female `r spp` and so unsexed fish were excluded. 
This results in `r ifelse(params$area == "North", 60, 504)`
unsexed fish excluded from the CAAL distributions, or approximately
`r ifelse(params$area == "North", "one", "fifteen")` percent of the aged fish.
Table \ref{tab:sample-size-age} show sample sizes. Sensitivities to using the CAAL
approach were explored by replacing with marginal age distributions. 

#### \acrlong{s-tri} ages

Age data preparation follow the same methods as the WCBTS length data. 
The \gls{s-tri} age-frequency data were included in the model 
as CAAL, and marginal age compositions were explored as sensitivities.
Figure \ref{fig:tri-ageComp} shows the age frequency data for the \gls{s-tri}.
Table \ref{tab:sample-size-age} shows sample sizes.

#### \Glsentrylong{s-tri} ages

Ages from the Hook and Line survey were available for the years 2017 - 2019. 
The age distribution of survey catches in each year 
was summarized using age bins from 0 to 20 years, in increments of one year. The last bin 
includes all fished aged to be greater than 20 years.
The Hook and Line Survey age-frequency data were included in the model as CAAL,
and marginal age compositions were explored as sensitivities.
Figure \ref{fig:hkl-ageComp} shows the age frequency data for the Hook and Line Survey.
Table \ref{tab:sample-size-age} shows sample sizes.

#### Lam research ages

A random stratified subsample by size and sex was selected per region for ageing and genetics analysis. 
The age composition data are therefore used as CAAL, and are not expanded.
Figure \ref{fig:lam-ageComp} shows the age frequency distributions. 
Table \ref{tab:sample-size-length} shows sample sizes.

